<a href="https://colab.research.google.com/github/sergioGarcia91/SeismicUP/blob/main/03_Analisis_de_subcatalogos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En este notebook se procederá con el análisis del catálogo sísmico dividiéndolo en tres subcatalogos:

1. `FC` (Full Catalog): corresponde a todos los eventos descargados.
2. `BSN` (Bucaramanga Seismic Nest Catalog): corresponde a los eventos asociados al área de estudio de García-Arias et al. (2026).
3. `CC` (Campo Colorado Catalog): corresponde a los eventos contenidos en un área de 100x100 km, centrada en el punto de referencia del Campo Colorado (X = 4'919.222,973; Y = 2'308.553,476; EPSG:9377).

A continuación se presentan los límites espaciales de cada catálogo expresados en coordenadas geográficas EPSG:4326:

| Catálogo | Longitud (min, max) | Latitud (min, max) |
| :------: | :-----------------: | :----------------: |
|    FC    |    -76.00, -71.00   |     3.00, 11.00    |
|    BSN   |    -73.40, -72.80   |     6.50, 7.10     |
|    CC    |    -74.19, -73.26   |     6.32, 7.25     |

# Inicio

In [ ]:
!git clone https://github.com/sergioGarcia91/SeismicUP.git

Cloning into 'SeismicUP'...
remote: Enumerating objects: 529, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 529 (delta 134), reused 0 (delta 0), pack-reused 301 (from 1)
Receiving objects: 100% (529/529), 23.17 MiB | 18.38 MiB/s, done.
Resolving deltas: 100% (282/282), done.

In [ ]:
# para incluir la libreria clonada
import sys
sys.path.append("/content/SeismicUP")

import seismicup as sup

In [ ]:
!pip -q install python-calamine

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 935.1/935.1 kB 13.7 MB/s eta 0:00:00

In [ ]:
!pip3 install contextily

Collecting contextily
  Downloading contextily-1.7.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (from contextily) (2.4.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from contextily) (3.10.0)
Collecting mercantile (from contextily)
  Downloading mercantile-1.2.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from contextily) (11.3.0)
Requirement already satisfied: rasterio in /usr/local/lib/python3.12/dist-packages (from contextily) (1.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from contextily) (2.32.4)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from contextily) (1.5.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from contextily) (2026.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy->contextily) (2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->contextily) (2.9.0.post0)
Requirement already satisfied: click>=3.0 in /usr/local/lib/python3.12/dist-packages (from mercantile->contextily) (8.4.1)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio->contextily) (2.4.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio->contextily) (26.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from rasterio->contextily) (2026.5.20)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio->contextily) (0.7.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->contextily) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->contextily) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->contextily) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->contextily) (1.17.0)
Downloading contextily-1.7.0-py3-none-any.whl (16 kB)
Downloading mercantile-1.2.1-py3-none-any.whl (14 kB)
Installing collected packages: mercantile, contextily
Successfully installed contextily-1.7.0 mercantile-1.2.1

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import seaborn as sns
import os
import re
import contextily as cx #para el basemap en geopandas
import xyzservices.providers as xyz #para escoger el basemap
import seismicup as sup
import urllib.request
import matplotlib.font_manager as fm
import random

from matplotlib.colors import LogNorm # para la escala logaritmica de los colores
from matplotlib.ticker import LogFormatter, LogLocator # escala log
from scipy import stats # regresion lineal

# Conectar al Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Cambiar Fuente

In [ ]:
sup.plots.get_TimesNewRoman_font()

# Paths

In [ ]:
path_save_figures = ''

In [ ]:
path_datasets = '/content/SeismicUP/Datasets_'

os.listdir(path_datasets)

['Cat_sis_SGC_TECTO_feb2014_2024',
 'Cat_sis_SGC_mar2018_2024',
 'Cat_mec_focal_tensor_mom_SGC_2014_2024',
 'README.md',
 'Cat_sis_SGC_jun1993_feb2018',
 'Cat_sis_SGC_LBG_jun1993_2021']

# Cargar catalogos

In [ ]:
lista_catalogos = ['Cat_sis_SGC_jun1993_feb2018',
                   'Cat_sis_SGC_mar2018_2024',
                   'Cat_sis_SGC_TECTO_feb2014_2024',
                   'Cat_sis_SGC_LBG_jun1993_2021']

for i in lista_catalogos:
  cantidad_archivos = len(os.listdir(os.path.join(path_datasets, i)))
  print(f'{i} = ', cantidad_archivos)

Cat_sis_SGC_jun1993_feb2018 =  26
Cat_sis_SGC_mar2018_2024 =  8
Cat_sis_SGC_TECTO_feb2014_2024 =  13
Cat_sis_SGC_LBG_jun1993_2021 =  29

In [ ]:
df_general = pd.DataFrame(columns=['Fecha-Hora UTC',
                                   'Latitud', # grados
                                   'Longitud', # grados
                                   'Profundidad [km]',
                                   'Magnitud',
                                   'Tipo Magnitud',
                                   'Error Latitud [km]',
                                   'Error Longitud [km]',
                                   'Error Profundidad [km]',
                                   'Numero de Fases',
                                   'RMS [seg]',
                                   'Gap', # grados
                                   'Departamento',
                                   'Municipio',
                                   ])

df_general.head()

Empty DataFrame
Columns: [Fecha-Hora UTC, Latitud, Longitud, Profundidad [km], Magnitud, Tipo Magnitud, Error Latitud [km], Error Longitud [km], Error Profundidad [km], Numero de Fases, RMS [seg], Gap, Departamento, Municipio]
Index: []

## Catalogo SGC 1

In [ ]:
path_catalogo = os.path.join(path_datasets, 'Cat_sis_SGC_jun1993_feb2018')
os.listdir(path_catalogo)

df_SGC_1 = df_general.copy()

for i in os.listdir(path_catalogo)[:]:
  if i.endswith('.xlsx'):
    print('-----'*3)
    print('File: ', i)
    print('-----'*3)
    df_temp_1 = sup.io.crear_catalogo_SGC_1(path_catalogo=path_catalogo,
                                            file_excel=i)

    df_SGC_1 = pd.concat([df_SGC_1, df_temp_1], ignore_index=True)
    df_SGC_1.reset_index(drop=True, inplace=True)

    del df_temp_1

---------------
File:  Cat_sis_SGC_2010.xlsx
---------------

['ANTIOQUIA' 'SANTANDER' 'CESAR' 'BOYACA' 'QUINDIO' 'VALLE DEL CAUCA'
 'TOLIMA' 'CUNDINAMARCA' 'CALDAS' 'CORDOBA' 'CASANARE' 'RISARALDA' 'META'
 'NORTE DE SANTANDER' 'BOLIVAR' 'ARAUCA' 'HUILA' 'SUCRE' 'LA GUAJIRA'
 'MAGDALENA']

['PUERTO BERRIO' 'SAN ANDRES' 'LOS SANTOS' 'CEPITA' 'SABANA DE TORRES'
 'CURUMANI' 'SABOYA' 'HATO' 'CALARCA' 'VALDIVIA' 'OBANDO' 'RIOBLANCO'
 'SAN PABLO DE BORBUR' 'CUCUNUBA' 'BARBOSA' 'VELEZ' 'EL CARMEN'
 'JERUSALEN' 'PALESTINA' 'BETULIA' 'ZAPATOCA' 'EL PLAYON'
 'SANTA HELENA DEL OPON' 'SUSA' 'PUERTO LIBERTADOR' 'OIBA' 'LA SALINA'
 'SAN VICENTE DE CHUCURI' 'CARTAGO' 'BALBOA' 'EL DORADO' 'ITUANGO'
 'CACHIRA' 'COPER' 'PUERTO PARRA' 'LA JAGUA DE IBIRICO' 'LEJANIAS'
 'CACERES' 'UTICA' 'ANORI' 'UBATE' 'LENGUAZAQUE' 'TIQUISIO' 'HERRAN'
 'GALAN' 'SURATA' 'MACANAL' 'MACEO' 'MUZO' 'CUBARA' 'BRICENO' 'TUNUNGUA'
 'NORCASIA' 'ALEJANDRIA' 'CHIMA' 'JESUS MARIA' 'MOGOTES' 'PISVA'
 'SAN PEDRO' 'ARENAL' 'EL PASO' 'GUAVATA' 'CABRERA' 'PIEDECUESTA'
 'BUENAVISTA' 'CHIPATA' 'GUACA' 'URIBE' 'PAUNA' 'CONCEPCION' 'ARAUQUITA'
 'COLOMBIA' 'PULI' 'MOLAGAVITA' 'GAMBITA' 'JORDAN' 'CAUCASIA'
 'ALTOS DEL ROSARIO' 'LA DORADA' 'LERIDA' 'RONCESVALLES' 'ORTEGA'
 'GUACHETA' 'PUEBLO NUEVO' 'PAEZ' 'TOGUI' 'VICTORIA' 'TAURAMENA' 'ARMERO'
 'CHAMEZA' 'BOLIVAR' 'MANAURE BALCON DEL CESAR' 'SAMANA' 'SANTANA'
 'PUERTO SANTANDER' 'GUICAN' 'VENADILLO' 'PUENTE NACIONAL' 'CHIQUINQUIRA'
 'SANTUARIO' 'VALLE DE SAN JOSE' 'SAN JOAQUIN' 'SUTAMARCHAN' 'MONGUA'
 'BECERRIL' 'SOGAMOSO' 'LA PALMA' 'CARMEN DE CARUPA' 'GUEPSA' 'PARAMO'
 'LANDAZURI' 'BARAYA' 'CALDAS' 'OTANCHE' 'LA BELLEZA' 'JARDIN'
 'BARRANCABERMEJA' 'GUAPOTA' 'SAN ALBERTO' 'GIRON' 'EL GUACAMAYO' 'SOCOTA'
 'FUQUENE' 'VILLAPINZON' 'SIMIJACA' 'SAN JERONIMO' 'ALVARADO'
 'SAN JOSE DE LA MONTANA' 'SOCHA' 'MANZANARES' 'MARIPI'
 'SAN LUIS DE GACENO' 'ABEJORRAL' 'PUERTO TRIUNFO' 'GUARANDA' 'PAJARITO'
 'SANTA ISABEL' 'CIMITARRA' 'SAN MIGUEL DE SEMA' 'AGUSTIN CODAZZI'
 'EL BAGRE' 'PELAYA' 'VILLANUEVA' 'AGUACHICA' 'SEVILLA' 'IBAGUE'
 'SARAVENA' 'SAN PABLO' 'ARATOCA' 'SAN CARLOS DE GUAROA' 'VENTAQUEMADA'
 'ANSERMANUEVO' 'CAICEDONIA' 'TIBU' 'VILLA DEL ROSARIO'
 'SANTA ROSA DEL SUR' 'LOURDES' 'SAMACA' 'MONIQUIRA' 'SABANALARGA' 'TAME'
 'YACOPI' 'CONFINES' 'SANTA FE ANTIOQUIA' 'SAN BENITO ABAD'
 'SAN JUAN DE RIOSECO' 'TARAZA' 'CUCUTILLA' 'ALBANIA'
 'SAN JOSE DE MIRANDA' 'CAPARRAPI' 'SANTA BARBARA' 'MONTENEGRO'
 'PUERTO WILCHES' 'LIBANO' 'EL COPEY' 'SIMACOTA' 'ANZOATEGUI' 'YONDO'
 'CHIRIGUANA' 'AQUITANIA' 'SALENTO' 'FORTUL' 'CUBARRAL' 'CIRCASIA'
 'CURITI' 'VEGACHI' 'RONDON' 'MAJAGUAL' 'BETANIA' 'GUADALUPE' 'QUETAME'
 'TAMARA' 'MATANZA' 'CERINZA' 'ROVIRA' 'MONTEBELLO' 'SANTA ROSA DE CABAL'
 'SUPIA' 'AGUADA' 'PIEDRAS' 'GUATICA' 'EL PENON' 'SALAZAR' 'PENSILVANIA'
 'VILLAMARIA' 'CARACOLI' 'MISTRATO' 'EL CALVARIO' 'EL COCUY' 'GIRARDOTA'
 'GACHANTIVA' 'TAUSA' 'PUERTO NARE' 'LEBRIJA' 'LA ESPERANZA' 'LA VICTORIA'
 'VILLARRICA' 'AMBALEMA' 'CONTRATACION' 'BELTRAN' 'TONA' 'BELMIRA'
 'CERRITO' 'SANTA ROSA DE OSOS' 'LA PENA' 'SALAMINA' 'PACORA' 'SOTAQUIRA'
 'SEGOVIA' 'HONDA' 'MEDINA' 'MONTECRISTO' 'COELLO' 'RIONEGRO' 'VALLEDUPAR'
 'GUARNE' 'ABREGO' 'CHOCONTA' 'PRADERA' 'SUCRE' 'ZARAGOZA' 'CUCUTA'
 'FIRAVITOBA' 'CANTAGALLO' 'RIO DE ORO' 'SOCORRO' 'TULUA' 'COTA'
 'MARIQUITA' 'FLORIDABLANCA' 'AYAPEL' 'EL TARRA' 'MESETAS' 'SAN RAFAEL'
 'SACAMA' 'HACARI' 'CAMPOHERMOSO' 'EL MOLINO' 'SAN BENITO' 'PUERTO BOYACA'
 'CAPITANEJO' 'SUAITA' 'PALMAS DEL SOCORRO' 'SAN ANTONIO' 'RAQUIRA'
 'FLORESTA' 'LA MESA' 'NATAGAIMA' 'CONVENCION' 'QUINCHIA' 'PEREIRA'
 'DOLORES' 'SAN ROQUE' 'BELALCAZAR' 'PURIFICACION' 'ARGELIA'
 'PUERTO SALGAR' 'ASTREA' 'GUAYABETAL' 'NUEVA GRANADA' 'MURILLO'
 'VILLAHERMOSA' 'LA MERCED' 'LA APARTADA' 'LABRANZAGRANDE' 'CHIVOLO'
 'CHITAGA' 'SIMITI' 'PIJINO DEL CARMEN' 'VISTAHERMOSA' 'MOSQUERA'
 'ALPUJARRA' 'PIJAO' 'SAN JUAN DE ARAMA' 'SARDINATA' 'PEQUE' 'DIBULLA'
 'GENOVA' 'SAN FRANCISCO' 'ANGOSTURA' 'TEORAMA' 'BARICHARA' 'SAN MARTIN'
 'NECHI' 'CARMEN DE APICALA' 'BARRANCO DE LOBA' 'LA PAZ' 'MAICAO'
 'SAN JUANITO' 'SAN GIL' 'CAJAMARCA' 'CHITA' 'GACHALA' 'REMEDIOS' 'JERICO'
 'SANTIAGO' 'MIRAFLORES' 'MONTERIA' 'CHAGUANI' 'RAGONVALIA'
 'QUEBRADANEGRA' 'MOMPOS' 'TELLO' 'PLANADAS' 'ALCALA'
 'GUAYABAL DE SIQUIMA' 'VALLE DE SAN JUAN' 'VIRACACHA' 'BARRANCA DE UPIA'
 'CHIMICHAGUA' 'PUEBLO BELLO' 'SATIVASUR' 'BUCARAMANGA' 'MACARAVITA'
 'MANI' 'AGUAZUL' 'FOMEQUE' 'SABANETA' 'CARCASI' 'PUERTO LLERAS'
 'LA JAGUA DEL PILAR' 'REMOLINO' 'RECETOR' 'CHINCHINA' 'TAMALAMEQUE'
 'PAILITAS' 'GUTIERREZ' 'PAIME' 'VILLAVICENCIO' 'ENCINO' 'PACHO' 'REGIDOR'
 'GRAMALOTE' 'PRADO' 'SAN DIEGO' 'CHAPARRAL' 'PESCA' 'AIPE' 'OLAYA'
 'COGUA' 'TIPACOQUE' 'SAN MARCOS' 'FLORIAN' 'LABATECA' 'RIOSUCIO'
 'SAN JOSE' 'VILLAGOMEZ' 'VILLAVIEJA' 'RIOVIEJO' 'VITERBO' 'COROMORO'
 'TIBASOSA' 'NOBSA' 'SAN PELAYO' 'DUITAMA' 'TUTAZA' 'HATO COROZAL'
 'VILLA CARO' 'ZIPAQUIRA' 'FILANDIA' 'CORDOBA' 'SINCE' 'VETAS' 'MONTERREY'
 'QUIPILE' 'CHOACHI' 'SAN CAYETANO' 'GAMARRA' 'EL ZULIA' 'YARUMAL'
 'CHARALA' 'OCANA' 'PINILLOS' 'FLORIDA' 'BELEN DE UMBRIA' 'ZONA BANANERA'
 'GUADUAS' 'TARSO' 'CIUDAD BOLIVAR' 'TOLEDO' 'SAN JOSE DE PARE' 'FREDONIA'
 'YOLOMBO' 'CICUCO' 'BUCARASICA' 'SAN FERNANDO' 'SOACHA' 'CHIVOR'
 'SAN JACINTO DEL CAUCA' 'BOSCONIA' 'ONZAGA' 'SAN CALIXTO' 'AMALFI'
 'ARMENIA' 'TENERIFE' 'TUTA' 'BARRANCAS' 'SAN LUIS' 'NARINO' 'TINJACA'
 'GONZALEZ' 'SAN EDUARDO' 'HISPANIA' 'SASAIMA' 'FALAN' 'ANDES'
 'CAMPAMENTO' 'LA GLORIA' 'SACHICA' 'BELEN' 'PAZ DE ARIPORO' 'CABUYARO'
 'ZARZAL' 'CALIFORNIA' 'CASTILLA LA NUEVA' 'MONGUI' 'LA PLAYA' 'OCAMONTE'
 'LA CELIA' 'VALPARAISO' 'TASCO' 'MALAGA' 'CHISCAS' 'SALDANA' 'FILADELFIA'
 'ACACIAS' 'CAIMITO' 'LA VIRGINIA' 'PALMAR' 'LA TEBAIDA' 'VIANI' 'SILOS'
 'PACHAVITA']

Index(['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)',
       'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO',
       'MUNICIPIO', '# FASES', 'RMS (Seg)', 'GAP (grados)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos Ml:  8655
Eventos Mw:  1
Eventos totales:  8656
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8656 entries, 0 to 8655
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          8656 non-null   object
 1   LATITUD (grados)        8656 non-null   float64
 2   LONGITUD (grados)       8656 non-null   float64
 3   PROFUNDIDAD (Km)        8656 non-null   float64
 4   Magnitud                8656 non-null   float64
 5   Tipo Magnitud           8656 non-null   object
 6   ERROR LATITUD (Km)      8656 non-null   float64
 7   ERROR LONGITUD (Km)     8656 non-null   float64
 8   ERROR PROFUNDIDAD (Km)  8656 non-null   float64
 9   # FASES                 8656 non-null   int64
 10  RMS (Seg)               8656 non-null   float64
 11  GAP (grados)            8656 non-null   int64
 12  Departamento            8656 non-null   object
 13  Municipio               8656 non-null   object
dtypes: float64(8), int64(2), object(4)
memory usage: 946.9+ KB
None
---------------
File:  Cat_sis_SGC_2000.xlsx
---------------

/tmp/ipykernel_7303/915494741.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_SGC_1 = pd.concat([df_SGC_1, df_temp_1], ignore_index=True)

['SANTANDER' 'CUNDINAMARCA' 'BOYACA' 'META' 'ARAUCA' 'CASANARE' 'CORDOBA'
 'ANTIOQUIA' 'NORTE DE SANTANDER' 'SUCRE' 'QUINDIO' 'TOLIMA' 'HUILA'
 'CESAR' 'BOLIVAR' 'CALDAS' 'RISARALDA' 'VALLE DEL CAUCA' 'MAGDALENA']

['LOS SANTOS' 'PUERTO PARRA' 'SAN VICENTE DE CHUCURI' 'PALMAR'
 'VILLAPINZON' 'CERRITO' 'ALBANIA' 'SAN ANDRES' 'ZAPATOCA' 'CHIQUINQUIRA'
 'MALAGA' 'CONCEPCION' 'VILLANUEVA' 'CEPITA' 'GAMBITA' 'EL GUACAMAYO'
 'LA PAZ' 'URIBE' 'FORTUL' 'EL CARMEN' 'LA SALINA' 'SUCRE' 'OTANCHE'
 'CIENAGA DE ORO' 'PAIME' 'MONIQUIRA' 'PIEDECUESTA' 'COCORNA' 'YONDO'
 'LA ESPERANZA' 'EL TARRA' 'CALDAS' 'MIRAFLORES' 'VELEZ' 'ZETAQUIRA'
 'SABANA DE TORRES' 'SANTA HELENA DEL OPON' 'SANTA BARBARA' 'BETULIA'
 'SEGOVIA' 'ABREGO' 'CUCUNUBA' 'GUACA' 'LEBRIJA' 'BUENAVISTA' 'GALAN'
 'MESETAS' 'LA UNION' 'CONTRATACION' 'NECHI' 'BUCARASICA' 'CUBARA'
 'SARAVENA' 'GACHALA' 'TAME' 'GUICAN' 'ARATOCA' 'ARMENIA' 'ARAUCA'
 'JERUSALEN' 'TARAZA' 'PUERTO NARE' 'JORDAN' 'TAMARA'
 'SAN JOSE DE MIRANDA' 'SOGAMOSO' 'SURATA' 'VALDIVIA' 'CIMITARRA'
 'PUERTO BERRIO' 'PACHO' 'RONCESVALLES' 'EL PLAYON' 'COLOMBIA' 'CHIPATA'
 'PULI' 'PALMAS DEL SOCORRO' 'PUERTO BOYACA' 'HATO' 'AQUITANIA' 'SIMACOTA'
 'SAN MARTIN' 'SABOYA' 'CALIFORNIA' 'SUAITA' 'TIQUISIO' 'SALENTO'
 'CAUCASIA' 'PUERTO WILCHES' 'FILADELFIA' 'CALARCA' 'PUENTE NACIONAL'
 'LANDAZURI' 'LA DORADA' 'MISTRATO' 'GUADUAS' 'PISVA' 'UBATE' 'SAN PABLO'
 'SAN CARLOS' 'BOLIVAR' 'ARAUQUITA' 'SAN MIGUEL DE SEMA'
 'SAN PABLO DE BORBUR' 'VILLARRICA' 'PAUNA' 'EL PENON' 'LA BELLEZA'
 'HACARI' 'SAN CAYETANO' 'VETAS' 'BARRANCABERMEJA' 'GIRON' 'FUQUENE'
 'SAN FRANCISCO' 'CHITARAQUE' 'BARBOSA' 'MONGUI' 'MONTECRISTO'
 'VILLA CARO' 'YACOPI' 'ZARAGOZA' 'AGUSTIN CODAZZI' 'LA PALMA'
 'SANTA ISABEL' 'PAJARITO' 'AMALFI' 'VICTORIA' 'CANTAGALLO' 'GUAVATA'
 'SUTAMARCHAN' 'CHARALA' 'TAURAMENA' 'PAZ DE RIO' 'JESUS MARIA' 'QUIPILE'
 'VALLE DE SAN JOSE' 'CHOCONTA' 'QUIMBAYA' 'LA JAGUA DE IBIRICO'
 'EL BAGRE' 'SAN JUAN DE RIOSECO' 'RESTREPO' 'GINEBRA' 'SAN ALBERTO'
 'MUZO' 'SUSA' 'BARICHARA' 'CACHIRA' 'FLORIAN' 'LA APARTADA' 'BELTRAN'
 'HONDA' 'SAN PEDRO' 'SACHICA' 'NUEVA GRANADA' 'LA TEBAIDA' 'ENCINO'
 'ARIGUANI' 'VITERBO' 'PUEBLO NUEVO' 'LABRANZAGRANDE' 'QUETAME'
 'LENGUAZAQUE' 'MOLAGAVITA' 'OIBA' 'CERINZA' 'BELEN' 'EL RETEN' 'CIRCASIA'
 'RAGONVALIA' 'CHAMEZA' 'NUNCHIA' 'CARTAGO' 'PAEZ' 'GUAMAL' 'CORDOBA'
 'CHIQUIZA' 'SANTO DOMINGO' 'SACAMA' 'CAPARRAPI' 'BARAYA' 'VILLAVICENCIO'
 'RIONEGRO' 'TURMEQUE' 'MEDELLIN' 'BRICENO' 'SEVILLA' 'CURITI'
 'SAN MARTIN DE LOBA' 'PAIPA' 'VIANI' 'QUEBRADANEGRA' 'GUACHETA'
 'CURUMANI' 'EL ESPINO' 'ANGELOPOLIS' 'COROMORO' 'ARMERO' 'FLORESTA'
 'PUERTO SANTANDER' 'SANTA ROSA DE VITERBO' 'PRADO' 'PARAMO' 'PIJAO'
 'DON MATIAS' 'SAMACA' 'ENCISO' 'VENTAQUEMADA' 'CAICEDONIA' 'CHIVOR'
 'OBANDO' 'LA PENA' 'AMBALEMA' 'SAN JUANITO' 'TUNUNGUA' 'CHIMICHAGUA'
 'ULLOA' 'FIRAVITOBA' 'MONGUA' 'ROVIRA' 'PESCA' 'LEJANIAS' 'SAN EDUARDO'
 'CAJAMARCA' 'FLORIDABLANCA' 'TIERRALTA' 'GRANADA' 'CUBARRAL' 'VENADILLO'
 'LA VIRGINIA' 'SANTA MARIA' 'CACERES' 'CHIMA' 'PUERTO SALGAR' 'MATANZA'
 'VILLA DE LEIVA' 'ANORI' 'LA VICTORIA' 'SANTA ROSA DEL SUR' 'GOMEZ PLATA'
 'HELICONIA' 'EL CASTILLO' 'TIBU' 'JERICO' 'CHITAGA' 'CHAGUANI'
 'GUTIERREZ' 'ARANZAZU' 'FALAN' 'SAN BENITO' 'TALAIGUA NUEVO' 'CABRERA'
 'PURIFICACION' 'OCAMONTE' 'COVARACHIA' 'IBAGUE' 'NORCASIA' 'VEGACHI'
 'CAMPAMENTO' 'QUINCHIA' 'CONFINES' 'SOCORRO' 'TONA' 'ARBOLEDAS' 'AGUADA'
 'ACHI' 'GUATAQUI' 'LERIDA' 'SAN GIL' 'BECERRIL' 'VALPARAISO' 'REMEDIOS']

Index(['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)',
       'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO',
       'MUNICIPIO', '# FASES', 'RMS (Seg)', 'GAP (grados)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos Ml:  2391
Eventos Mw:  0
Eventos totales:  2391
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2391 entries, 0 to 2390
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          2391 non-null   object
 1   LATITUD (grados)        2391 non-null   float64
 2   LONGITUD (grados)       2391 non-null   float64
 3   PROFUNDIDAD (Km)        2391 non-null   float64
 4   Magnitud                2391 non-null   float64
 5   Tipo Magnitud           2391 non-null   object
 6   ERROR LATITUD (Km)      2391 non-null   float64
 7   ERROR LONGITUD (Km)     2391 non-null   float64
 8   ERROR PROFUNDIDAD (Km)  2391 non-null   float64
 9   # FASES                 2391 non-null   int64
 10  RMS (Seg)               2391 non-null   float64
 11  GAP (grados)            2391 non-null   int64
 12  Departamento            2391 non-null   object
 13  Municipio               2391 non-null   object
dtypes: float64(8), int64(2), object(4)
memory usage: 261.6+ KB
None
---------------
File:  Cat_sis_SGC_2005.xlsx
---------------

['SANTANDER' 'BOYACA' 'BOLIVAR' 'QUINDIO' 'CUNDINAMARCA' 'TOLIMA'
 'ANTIOQUIA' 'CESAR' 'HUILA' 'SUCRE' 'VALLE DEL CAUCA'
 'NORTE DE SANTANDER' 'META' 'RISARALDA' 'LA GUAJIRA' 'CORDOBA' 'CALDAS'
 'MAGDALENA' 'CASANARE' 'ARAUCA']

['CEPITA' 'LOS SANTOS' 'OTANCHE' 'TIQUISIO' 'SALENTO' 'FUQUENE' 'BETULIA'
 'EL CARMEN' 'ZAPATOCA' 'PIEDECUESTA' 'SAN PABLO' 'ARMERO' 'SAN ANDRES'
 'ALVARADO' 'ITUANGO' 'ZARAGOZA' 'SAN VICENTE DE CHUCURI' 'SANTA BARBARA'
 'SABANA DE TORRES' 'GUACA' 'PUENTE NACIONAL' 'SAN ALBERTO' 'CHAGUANI'
 'BARBOSA' 'HATO' 'CHISCAS' 'CORDOBA' 'BARAYA' 'CALIFORNIA' 'SAN DIEGO'
 'SAN MIGUEL DE SEMA' 'CANTAGALLO' 'BRICENO' 'LEBRIJA' 'SUCRE' 'COLOMBIA'
 'ANORI' 'RONCESVALLES' 'CHARALA' 'BARRANCABERMEJA' 'LENGUAZAQUE' 'PAUNA'
 'GUICAN' 'SUTAMARCHAN' 'CUBARA' 'EL PASO' 'LA BELLEZA' 'PUERTO PARRA'
 'VILLA DE LEIVA' 'MARIQUITA' 'FALAN' 'SUSA' 'EL PENON' 'BUENAVISTA'
 'ORTEGA' 'SUAITA' 'PULI' 'EL PLAYON' 'LA VEGA' 'SURATA'
 'SANTA ROSA DEL SUR' 'VELEZ' 'ARATOCA' 'JORDAN' 'SANTA HELENA DEL OPON'
 'ANSERMANUEVO' 'EL TARRA' 'TARAZA' 'URIBE' 'PUERTO WILCHES' 'HONDA'
 'CHIPATA' 'MANAURE BALCON DEL CESAR' 'MONGUA' 'YACOPI' 'QUINCHIA' 'PRADO'
 'SABOYA' 'CUCUTILLA' 'AGUSTIN CODAZZI' 'ONZAGA' 'ALBANIA' 'VILLANUEVA'
 'PUERTO LIBERTADOR' 'BOLIVAR' 'ARCABUCO' 'LA PAZ' 'REMEDIOS' 'SAN GIL'
 'SOCOTA' 'EL BAGRE' 'VICTORIA' 'FLORIDABLANCA' 'CUCUNUBA' 'GIRON'
 'AMBALEMA' 'OCAMONTE' 'NECHI' 'RIO DE ORO' 'CABRERA' 'GALAN'
 'PUERTO BERRIO' 'PIJAO' 'CIMITARRA' 'CALDAS' 'EL BANCO' 'PUERTO NARE'
 'LA UVITA' 'CAMPOHERMOSO' 'SAN JUAN DEL CESAR' 'CHITAGA' 'MOGOTES'
 'CARACOLI' 'UBATE' 'AGUAZUL' 'ARENAL' 'GACHALA' 'PUERTO SANTANDER'
 'AYAPEL' 'LANDAZURI' 'SIMIJACA' 'CONCEPCION' 'CAUCASIA' 'AIPE'
 'PUERTO LOPEZ' 'JESUS MARIA' 'LEJANIAS' 'CHINACOTA' 'NORCASIA'
 'SAN FRANCISCO' 'FLORIAN' 'TAME' 'SAN LUIS' 'VALLE DE SAN JOSE' 'SACAMA'
 'IZA' 'SAN BENITO' 'UTICA' 'VILLA DEL ROSARIO' 'PAJARITO' 'CERRITO'
 'CONTRATACION' 'MAGANGUE' 'COROMORO' 'CHIMA' 'COVARACHIA' 'GINEBRA'
 'MONTECRISTO' 'SAMANA' 'CHAPARRAL' 'EL COCUY' 'SAN CALIXTO' 'NEIVA'
 'SAN JUANITO' 'ACACIAS' 'SAN JUAN DE RIOSECO' 'CHOCONTA' 'SILOS' 'PAEZ'
 'CHIQUINQUIRA' 'VILLAPINZON' 'SATIVASUR' 'PEQUE' 'TAURAMENA'
 'SAN JUAN DE ARAMA' 'FUENTE DE ORO' 'CHITA' 'TOTA' 'MESETAS'
 'SANTA SOFIA' 'TUTAZA' 'CAPARRAPI' 'VILLARRICA' 'ABREGO' 'LA VICTORIA'
 'MONTERREY' 'GUAVATA' 'CHAMEZA' 'DOLORES' 'PAILITAS' 'CARMEN DE VIBORAL'
 'LERIDA' 'SIMITI' 'RIONEGRO' 'SAN BERNARDO' 'YONDO' 'SALDANA' 'FLORESTA'
 'FORTUL' 'PUERTO TRIUNFO' 'CACERES' 'PELAYA' 'PINILLOS' 'TAMALAMEQUE'
 'PLANADAS' 'CUCUTA' 'GOMEZ PLATA' 'SAN CAYETANO' 'BALBOA' 'VALDIVIA'
 'FILANDIA' 'IBAGUE' 'COPER' 'GUATAQUI' 'VENADILLO' 'TEORAMA'
 'PUERTO RONDON' 'MAJAGUAL' 'ENCINO' 'GUADUAS' 'SOCHA' 'HACARI'
 'CARMEN DE CARUPA' 'SANTA FE ANTIOQUIA' 'EL GUACAMAYO' 'PALMAR'
 'CONVENCION' 'CHARTA' 'VALLE DE SAN JUAN' 'CARMEN DE APICALA'
 'BARRANCO DE LOBA' 'TASCO' 'ROVIRA' 'PIEDRAS' 'SANTANA' 'ANZOATEGUI'
 'SAN PABLO DE BORBUR' 'PAIPA' 'GUADALUPE' 'MOLAGAVITA' 'ZAPAYAN'
 'SABANAS DE SAN ANGEL' 'VALLEDUPAR' 'SAN MARCOS' 'PUERTO BOYACA'
 'LA ESPERANZA' 'DIBULLA' 'SANTA ROSA DE CABAL' 'QUIPAMA' 'SACHICA'
 'LA VIRGINIA' 'MARSELLA' 'FIRAVITOBA' 'OCANA' 'PUERTO SALGAR' 'QUIPILE'
 'ASTREA' 'TUNUNGUA' 'ARBOLEDAS' 'LA DORADA' 'CARTAGO' 'GUTIERREZ' 'MANI'
 'CANASGORDAS' 'OIBA' 'SEGOVIA' 'CAJAMARCA' 'SAN ANTONIO' 'CAMPAMENTO'
 'SAN JUAN NEPOMUCENO' 'GUAPOTA' 'PUEBLO BELLO' 'CALARCA' 'AGUADA'
 'CISNEROS' 'SALAZAR' 'AGUADAS' 'VEGACHI' 'VITERBO' 'MATANZA' 'SAN MIGUEL'
 'TONA' 'CAPITANEJO' 'SATIVANORTE' 'SAN PEDRO' 'BERBEO' 'EL MOLINO'
 'GACHANTIVA' 'GIRARDOT' 'GARAGOA' 'ALPUJARRA' 'SOGAMOSO' 'RAGONVALIA'
 'BELALCAZAR' 'GUAYABETAL' 'APIA' 'SARDINATA' 'AMALFI' 'PISVA' 'MARIPI'
 'BOGOTA.DISTRITO CAPITAL' 'MUZO' 'VILLA CARO' 'PUERTO RICO' 'TAMARA'
 'GONZALEZ' 'RIOBLANCO' 'LA SALINA' 'SARAVENA' 'CICUCO' 'BECERRIL'
 'GAMEZA' 'CHITARAQUE' 'CHINCHINA' 'SAN CARLOS DE GUAROA' 'PEREIRA' 'TIBU'
 'TOGUI' 'NATAGAIMA' 'SAN EDUARDO' 'LA PINTADA' 'NARINO' 'VISTAHERMOSA'
 'ANAPOIMA' 'LA JAGUA DE IBIRICO' 'LA TEBAIDA' 'AQUITANIA' 'HERRAN'
 'ZIPACON' 'SUSACON' 'EL CALVARIO' 'CURITI']

Index(['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)',
       'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO',
       'MUNICIPIO', '# FASES', 'RMS (Seg)', 'GAP (grados)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos Ml:  4295
Eventos Mw:  0
Eventos totales:  4295
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4295 entries, 0 to 4294
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          4295 non-null   object
 1   LATITUD (grados)        4295 non-null   float64
 2   LONGITUD (grados)       4295 non-null   float64
 3   PROFUNDIDAD (Km)        4295 non-null   float64
 4   Magnitud                4295 non-null   float64
 5   Tipo Magnitud           4295 non-null   object
 6   ERROR LATITUD (Km)      4295 non-null   float64
 7   ERROR LONGITUD (Km)     4295 non-null   float64
 8   ERROR PROFUNDIDAD (Km)  4295 non-null   float64
 9   # FASES                 4295 non-null   int64
 10  RMS (Seg)               4295 non-null   float64
 11  GAP (grados)            4295 non-null   int64
 12  Departamento            4295 non-null   object
 13  Municipio               4295 non-null   object
dtypes: float64(8), int64(2), object(4)
memory usage: 469.9+ KB
None
---------------
File:  Cat_sis_SGC_2001.xlsx
---------------

['SANTANDER' 'CUNDINAMARCA' 'NORTE DE SANTANDER' 'ARAUCA' 'ANTIOQUIA'
 'TOLIMA' 'BOYACA' 'CESAR' 'CASANARE' 'QUINDIO' 'BOLIVAR' 'HUILA' 'META'
 'RISARALDA' 'CORDOBA' 'CALDAS' 'VALLE DEL CAUCA' 'LA GUAJIRA' 'MAGDALENA'
 'SUCRE' 'CAUCA']

['GUACA' 'CEPITA' 'LOS SANTOS' 'PIEDECUESTA' 'GUAYABETAL'
 'SANTA HELENA DEL OPON' 'ABREGO' 'ZAPATOCA' 'PUENTE NACIONAL'
 'PUERTO RONDON' 'PUERTO NARE' 'EL PENON' 'ARMERO' 'LA BELLEZA'
 'CIMITARRA' 'PAYA' 'BETULIA' 'SAN ANDRES' 'CACHIRA' 'PUERTO SANTANDER'
 'GUADUAS' 'CALDAS' 'ARATOCA' 'PUERTO BOYACA' 'MOGOTES' 'JORDAN' 'LA PAZ'
 'MOLAGAVITA' 'SAN MARTIN' 'LERIDA' 'HATO' 'SABOYA' 'SANTA BARBARA'
 'OTANCHE' 'CURITI' 'TOGUI' 'FLORIDABLANCA' 'LA SALINA' 'PUERTO BERRIO'
 'PALMAR' 'CORDOBA' 'PIJAO' 'SAN GIL' 'SIMACOTA' 'EL CARMEN' 'HACARI'
 'SAN LUIS' 'COCORNA' 'SUSA' 'IBAGUE' 'MARIQUITA' 'TOLEDO' 'BRICENO'
 'SAN FRANCISCO' 'LA ESPERANZA' 'SABANA DE TORRES' 'TONA' 'MONTECRISTO'
 'MONTERREY' 'ALVARADO' 'VENADILLO' 'LA VICTORIA' 'BARICHARA' 'EL TARRA'
 'PAUNA' 'YONDO' 'UBATE' 'FUQUENE' 'LENGUAZAQUE' 'LANDAZURI' 'SACAMA'
 'MARIPI' 'TELLO' 'SABANALARGA' 'URIBE' 'TAURAMENA' 'AGUAZUL' 'SANTUARIO'
 'YACOPI' 'CALARCA' 'CHAGUANI' 'BECERRIL' 'SILVANIA' 'GIRON' 'ALBANIA'
 'SAN VICENTE DE CHUCURI' 'PLANETA RICA' 'CONTRATACION'
 'SANTA ROSA DEL SUR' 'JERUSALEN' 'VILLANUEVA' 'CUBARA' 'CAMPOHERMOSO'
 'LA PLAYA' 'ARMENIA' 'CIRCASIA' 'PULI' 'SAN JUANITO' 'MONTENEGRO'
 'SAN JOSE DE MIRANDA' 'COROMORO' 'CURUMANI' 'CUCUTILLA' 'CHIQUINQUIRA'
 'ARENAL' 'BELTRAN' 'SAN JUAN DE ARAMA' 'REMEDIOS' 'SALENTO' 'FLORIAN'
 'SANTA MARIA' 'PUERTO PARRA' 'NECHI' 'PAILITAS' 'TIQUISIO' 'GENOVA'
 'SIMIJACA' 'CHAMEZA' 'AIPE' 'VILLA CARO' 'LABATECA' 'SAN BENITO'
 'MESETAS' 'SOCOTA' 'NOBSA' 'SUPIA' 'VILLAPINZON' 'LA MERCED' 'COLOMBIA'
 'VILLARRICA' 'OCAMONTE' 'SAN PABLO' 'PALMAS DEL SOCORRO' 'ANZOATEGUI'
 'BARAYA' 'LA VIRGINIA' 'GAMBITA' 'ACACIAS' 'NORCASIA' 'LA TEBAIDA'
 'SALDANA' 'BARBOSA' 'ANSERMA' 'AGUSTIN CODAZZI' 'ALCALA' 'JESUS MARIA'
 'RONCESVALLES' 'SAN JACINTO DEL CAUCA' 'SAN MIGUEL DE SEMA' 'APIA'
 'CAJAMARCA' 'PEQUE' 'MONIQUIRA' 'EL BAGRE' 'EL PLAYON' 'ALPUJARRA'
 'BARRANCABERMEJA' 'CARTAGO' 'PIEDRAS' 'SUCRE' 'CHIPATA' 'PAEZ'
 'PUERTO TRIUNFO' 'SAN PABLO DE BORBUR' 'ARAUQUITA' 'RISARALDA' 'YOLOMBO'
 'SURATA' 'CACERES' 'TAMALAMEQUE' 'VELEZ' 'BOLIVAR' 'RIONEGRO' 'GUATAQUI'
 'HONDA' 'CUCUNUBA' 'ROVIRA' 'TARAZA' 'VICTORIA' 'SOCORRO' 'EL MOLINO'
 'PINCHOTE' 'DUITAMA' 'SEGOVIA' 'AMBALEMA' 'SAMACA' 'FORTUL' 'LEJANIAS'
 'LEBRIJA' 'LOURDES' 'TEORAMA' 'ZARAGOZA' 'MUZO' 'CONFINES' 'CHIMICHAGUA'
 'TUNUNGUA' 'PEREIRA' 'TAMESIS' 'CARACOLI' 'FALAN' 'LIBANO' 'CHIRIGUANA'
 'YALI' 'QUIPILE' 'JARDIN' 'AYAPEL' 'SAN JOSE' 'HERVEO' 'GALAN'
 'PALESTINA' 'PUERTO SALGAR' 'LA APARTADA' 'ITUANGO' 'GACHALA' 'CHARALA'
 'BETANIA' 'SAN JOSE DE LA MONTANA' 'CANASGORDAS' 'GUADALUPE' 'SARAVENA'
 'SEVILLA' 'SAN CAYETANO' 'LA JAGUA DE IBIRICO' 'ORTEGA' 'BITUIMA'
 'SANTA BARBARA DE PINTO' 'CAUCASIA' 'SANTA ROSA DE CABAL' 'SACHICA'
 'PISVA' 'MANAURE BALCON DEL CESAR' 'CUBARRAL' 'CARTAGENA DE INDIAS'
 'SAN LUIS DE GACENO' 'CHINCHINA' 'SAN EDUARDO' 'PUEBLO NUEVO'
 'PUERTO WILCHES' 'MAICAO' 'MARSELLA' 'LABRANZAGRANDE' 'VALLE DE SAN JUAN'
 'CONVENCION' 'OCANA' 'SILOS' 'DOLORES' 'LA PALMA' 'EL PASO' 'MURILLO'
 'TAME' 'PLANADAS' 'SAN DIEGO' 'QUETAME' 'PRADERA' 'CAPITANEJO'
 'SAN JUAN DE RIOSECO' 'BUCARASICA' 'CERRITO' 'CALIFORNIA' 'EL COLEGIO'
 'BUENAVISTA' 'YARUMAL' 'MAJAGUAL' 'MACEO' 'GUARANDA' 'CORRALES'
 'SATIVASUR' 'VILLAVIEJA' 'SAN BENITO ABAD' 'LA DORADA'
 'SAN JUAN DEL CESAR' 'CIUDAD BOLIVAR' 'UTICA' 'CARCASI'
 'BARRANCO DE LOBA' 'HERRAN' 'BUCARAMANGA' 'CONCEPCION' 'CARMEN DE CARUPA'
 'LA JAGUA DEL PILAR' 'RIOVIEJO' 'TASCO' 'SANTO DOMINGO' 'GUEPSA'
 'MIRANDA' 'SAN ALBERTO' 'RESTREPO' 'GUAVATA' 'TIBASOSA' 'PURIFICACION'
 'GUICAN' 'JUNIN' 'GAMA' 'CAPARRAPI' 'VETAS' 'CANTAGALLO' 'SAN MARCOS'
 'MALAGA' 'SAN ANTONIO' 'CHITAGA' 'CHISCAS' 'SANTA ROSA DE VITERBO'
 'SABANAS DE SAN ANGEL' 'FLORIDA' 'TIBU' 'NATAGAIMA' 'TUTAZA'
 'PUERTO LLERAS' 'PUERTO LIBERTADOR' 'CHIMA' 'CHIVOR' 'MATANZA'
 'LA GLORIA' 'FONSECA' 'ARBOLEDAS' 'EL GUACAMAYO' 'AQUITANIA' 'VIANI'
 'CHIVOLO' 'MORALES' 'SAN CARLOS' 'AMALFI']

Index(['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)',
       'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO',
       'MUNICIPIO', '# FASES', 'RMS (Seg)', 'GAP (grados)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos Ml:  3811
Eventos Mw:  10
Eventos totales:  3821
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3821 entries, 0 to 3820
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          3821 non-null   object
 1   LATITUD (grados)        3821 non-null   float64
 2   LONGITUD (grados)       3821 non-null   float64
 3   PROFUNDIDAD (Km)        3821 non-null   float64
 4   Magnitud                3821 non-null   float64
 5   Tipo Magnitud           3821 non-null   object
 6   ERROR LATITUD (Km)      3821 non-null   float64
 7   ERROR LONGITUD (Km)     3821 non-null   float64
 8   ERROR PROFUNDIDAD (Km)  3821 non-null   float64
 9   # FASES                 3821 non-null   int64
 10  RMS (Seg)               3821 non-null   float64
 11  GAP (grados)            3821 non-null   int64
 12  Departamento            3821 non-null   object
 13  Municipio               3821 non-null   object
dtypes: float64(8), int64(2), object(4)
memory usage: 418.1+ KB
None
---------------
File:  Cat_sis_SGC_1994.xlsx
---------------

['SANTANDER' 'CUNDINAMARCA' 'BOYACA' 'ANTIOQUIA' 'TOLIMA' 'MAGDALENA'
 'HUILA' 'CESAR' 'NORTE DE SANTANDER' 'CAUCA' 'CASANARE' 'BOLIVAR'
 'VALLE DEL CAUCA' 'META' 'RISARALDA' 'CALDAS' 'LA GUAJIRA' 'CORDOBA'
 'QUINDIO' 'ARAUCA' 'SUCRE']

['CEPITA' 'VIANI' 'SABOYA' 'GUACA' 'CHAGUANI' 'PULI' 'PUERTO TRIUNFO'
 'SAN ANDRES' 'PIEDECUESTA' 'VILLANUEVA' 'ARATOCA' 'LOS SANTOS'
 'EL CARMEN' 'HONDA' 'GIRON' 'ARMERO' 'CUBARA' 'PIVIJAY' 'JORDAN'
 'COLOMBIA' 'SEGOVIA' 'AMBALEMA' 'BETULIA' 'ZAPATOCA' 'BUENAVISTA'
 'SANTA BARBARA' 'AGUACHICA' 'SANTA HELENA DEL OPON' 'LIBORINA' 'CURITI'
 'FLORIDABLANCA' 'CABRERA' 'VILLARRICA' 'ABEJORRAL' 'CIMITARRA' 'PLANADAS'
 'MARINILLA' 'VEGACHI' 'SAN LUIS DE GACENO' 'SANTA MARIA' 'BOCHALEMA'
 'RIOBLANCO' 'PAYA' 'BETANIA' 'LABRANZAGRANDE' 'MONGUI' 'BARBOSA'
 'SAN JUAN DE RIOSECO' 'MIRANDA' 'SACAMA' 'LANDAZURI' 'GAMEZA' 'GAMBITA'
 'TUNUNGUA' 'EL PENON' 'PUERTO BOYACA' 'LA SALINA' 'CHIPATA' 'BELTRAN'
 'SAN PABLO DE BORBUR' 'SAN VICENTE DE CHUCURI' 'CALDAS' 'PUERTO BERRIO'
 'PUERTO SALGAR' 'GONZALEZ' 'MONTECRISTO' 'OBANDO' 'SUSA' 'CERRITO'
 'CONCEPCION' 'URIBE' 'SALGAR' 'BITUIMA' 'RAQUIRA' 'YACOPI' 'BOLIVAR'
 'MARIQUITA' 'RIONEGRO' 'MISTRATO' 'MARIPI' 'COPER' 'PAILITAS' 'QUIPAMA'
 'AGUADAS' 'VENADILLO' 'LA VICTORIA' 'BARICHARA' 'PALMAR' 'PAUNA'
 'VALLE DE SAN JUAN' 'SAN JUAN DEL CESAR' 'OTANCHE' 'PUEBLO NUEVO'
 'TARAZA' 'SAN PEDRO' 'SEVILLA' 'SAN PABLO' 'JESUS MARIA' 'LA MESA'
 'PUERTO NARE' 'SURATA' 'NATAGAIMA' 'ALBANIA' 'TOLEDO' 'GALAN' 'COROMORO'
 'SAMANA' 'TIBU' 'SAN FRANCISCO' 'EL BAGRE' 'SAN LUIS' 'SAN JUANITO'
 'MOLAGAVITA' 'LERIDA' 'DOLORES' 'CHISCAS' 'RONCESVALLES' 'CAUCASIA'
 'BRICENO' 'SAN ANTONIO' 'YONDO' 'CARMEN DE CARUPA' 'ITUANGO' 'NOBSA'
 'CIRCASIA' 'YALI' 'SABANALARGA' 'SIMIJACA' 'MONTERREY' 'NORCASIA'
 'BECERRIL' 'ANORI' 'LA BELLEZA' 'PUERTO WILCHES' 'CURUMANI' 'LENGUAZAQUE'
 'NEIVA' 'CHIQUINQUIRA' 'GUAVATA' 'VICTORIA' 'CAJAMARCA' 'ALVARADO'
 'PARATEBUENO' 'OIBA' 'CHAMEZA' 'QUINCHIA' 'OCAMONTE' 'JUNIN' 'MONIQUIRA'
 'CABUYARO' 'LEJANIAS' 'FALAN' 'ARAUQUITA' 'SARAVENA' 'CALARCA' 'GUACHETA'
 'SAN JOAQUIN' 'GUTIERREZ' 'SAN GIL' 'BARAYA' 'LIBANO' 'ENCINO' 'PIEDRAS'
 'CHOACHI' 'HERRAN' 'GRANADA' 'VILLA DEL ROSARIO' 'PAJARITO' 'FORTUL'
 'EL ZULIA' 'PUERTO PARRA' 'CHARALA' 'ABREGO' 'RIO DE ORO' 'ONZAGA'
 'SUTATAUSA' 'JERICO' 'PURIFICACION' 'RIOVIEJO' 'GUADUAS' 'SAN MIGUEL'
 'SAN CAYETANO' 'MARSELLA' 'SIMITI' 'RISARALDA' 'SANTA ROSA DEL SUR'
 'NECHI' 'SUCRE' 'GUATAQUI' 'MANIZALES' 'RAGONVALIA' 'QUETAME'
 'SABANA DE TORRES' 'PAIPA' 'LA DORADA' 'VELEZ' 'REMEDIOS' 'CUBARRAL'
 'QUIPILE' 'ARENAL' 'HATO' 'CARTAGO' 'LA PAZ' 'RIOSUCIO' 'LEBRIJA' 'PEQUE'
 'CUCUNUBA' 'LA ESPERANZA' 'UNE' 'SONSON' 'AGUAZUL' 'CACHIRA'
 'PUERTO SANTANDER' 'VILLA DE LEIVA' 'TORIBIO' 'VILLAVIEJA' 'TARSO'
 'MACEO' 'MOTAVITA' 'CAPARRAPI' 'LA PALMA' 'FLORIAN' 'CAMPAMENTO' 'CHIMA'
 'MURILLO' 'BARRANCABERMEJA' 'CANASGORDAS' 'EL PLAYON' 'TIQUISIO'
 'SIMACOTA' 'SOCORRO' 'PALMAS DEL SOCORRO' 'VETAS' 'ROVIRA' 'BURITICA'
 'AIPE' 'CONTRATACION' 'EL ROBLE' 'COTA' 'SAN EDUARDO' 'ZARAGOZA' 'MUZO'
 'UTICA' 'GUEPSA' 'ZETAQUIRA' 'PUEBLO BELLO' 'DUITAMA' 'LOURDES'
 'LA TEBAIDA' 'ATACO' 'AMALFI' 'PUENTE NACIONAL' 'HACARI' 'EL TARRA'
 'ARBOLEDAS' 'BERBEO' 'PINILLOS' 'SAN MIGUEL DE SEMA' 'AGUSTIN CODAZZI'
 'SAN ALBERTO' 'YARUMAL' 'TONA' 'GACHALA' 'COMBITA' 'EL CALVARIO']

Index(['FECHA', 'HORA_UTC', 'LATITUD (grados)', 'LONGITUD (grados)',
       'PROFUNDIDAD (Km)', 'MAGNITUD Ml', 'MAGNITUD Mw', 'DEPARTAMENTO',
       'MUNICIPIO', '# FASES', 'RMS (Seg)', 'GAP (grados)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos Ml:  2312
Eventos Mw:  0
Eventos totales:  2312
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2312 entries, 0 to 2311

In [ ]:
df_SGC_1['Catalogo'] = 'SGC 1'
df_SGC_1['Gap'] = df_SGC_1['Gap'].astype(float)
df_SGC_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145061 entries, 0 to 145060
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fecha-Hora UTC          145061 non-null  object
 1   Latitud                 145061 non-null  float64
 2   Longitud                145061 non-null  float64
 3   Profundidad [km]        145061 non-null  float64
 4   Magnitud                145061 non-null  float64
 5   Tipo Magnitud           145061 non-null  object
 6   Error Latitud [km]      144927 non-null  float64
 7   Error Longitud [km]     144927 non-null  float64
 8   Error Profundidad [km]  144927 non-null  float64
 9   Numero de Fases         145061 non-null  object
 10  RMS [seg]               144927 non-null  float64
 11  Gap                     144927 non-null  float64
 12  Departamento            145061 non-null  object
 13  Municipio               145061 non-null  object
 14  Catalogo                145061 non-null  object
dtypes: float64(9), object(6)
memory usage: 16.6+ MB

In [ ]:
df_SGC_1.head()

,Fecha-Hora UTC,Latitud,Longitud,Profundidad [km],Magnitud,Tipo Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],Numero de Fases,RMS [seg],Gap,Departamento,Municipio,Catalogo
0,2010-01-01 01:55:52,6.504,-74.471,4.0,1.6,Ml,10.0,4.2,11.9,5,0.6,220.0,ANTIOQUIA,PUERTO BERRIO,SGC 1
1,2010-01-01 04:19:45,6.775,-72.869,143.4,1.4,Ml,6.4,11.8,7.9,5,0.4,240.0,SANTANDER,SAN ANDRES,SGC 1
2,2010-01-01 07:33:57,6.773,-73.080,148.0,1.6,Ml,2.4,6.9,4.8,6,0.3,189.0,SANTANDER,LOS SANTOS,SGC 1
3,2010-01-01 07:40:27,6.776,-73.032,156.0,1.1,Ml,5.3,45.2,15.2,5,0.3,194.0,SANTANDER,CEPITA,SGC 1
4,2010-01-01 08:46:08,6.823,-73.023,137.6,1.9,Ml,5.4,10.2,11.4,9,0.5,135.0,SANTANDER,CEPITA,SGC 1

## Catalogo SGC 2

In [ ]:
path_catalogo = os.path.join(path_datasets, 'Cat_sis_SGC_mar2018_2024')
os.listdir(path_catalogo)

df_SGC_2 = df_general.copy()

for i in os.listdir(path_catalogo)[:]:
  if i.endswith('.xlsx'):
    print('-----'*3)
    print('File: ', i)
    print('-----'*3)
    df_temp_1 = sup.io.crear_catalogo_SGC_2(path_catalogo=path_catalogo,
                                            file_excel=i)

    df_SGC_2 = pd.concat([df_SGC_2, df_temp_1], ignore_index=True)
    df_SGC_2.reset_index(drop=True, inplace=True)

    del df_temp_1

---------------
File:  Cat_sis_SGC_2020.xlsx
---------------

['SANTANDER' 'META' 'RISARALDA' 'CUNDINAMARCA' 'NORTE DE SANTANDER'
 'BOLÍVAR' 'CESAR' 'ANTIOQUIA' 'TOLIMA' 'CÓRDOBA' 'VALLE DEL CAUCA'
 'BOYACÁ' 'MAGDALENA' 'CALDAS' 'QUINDÍO' 'VENEZUELA' 'LA GUAJIRA' 'HUILA'
 'CASANARE' 'NORTE COLOMBIA' 'ARAUCA' 'SUCRE' 'MAR CARIBE' 'ATLÁNTICO']

['RIONEGRO' 'LOS SANTOS' 'ZAPATOCA' 'URIBE' 'SANTA ROSA DE CABAL'
 'MESETAS' 'SAN VICENTE DE CHUCURÍ' 'CUCUNUBÁ' 'CHITAGÁ'
 'SAN MARTIN DE LOBA' 'YACOPÍ' 'PUERTO PARRA' 'AGUACHICA' 'EL CARMEN'
 'CIMITARRA' 'YONDÓ (CASABE)' 'LA PAZ' 'VILLANUEVA' 'BARICHARA' 'SIMACOTA'
 'FLORIÁN' 'CIUDAD BOLÍVAR' 'SAN MARTÍN' 'SAN BENITO' 'PLANADAS'
 'EL PLAYÓN' 'ACACÍAS' 'YOLOMBÓ' 'EL COPEY' 'AYAPEL' 'PURIFICACIÓN'
 'SABANA DE TORRES' 'PULÍ' 'LANDÁZURI' 'CHIRIGUANÁ' 'LA GLORIA'
 'LA ESPERANZA' 'SALGAR' 'CAICEDONIA' 'UBATÉ' 'SUCRE' 'RONCESVALLES'
 'SURATÁ' 'AGUSTÍN CODAZZI' 'GUAVATÁ' 'SANTUARIO' 'VÉLEZ' 'BOLIVAR'
 'PUERTO BOYACÁ' 'BETULIA' 'LEBRIJA' 'MARGARITA' 'VENADILLO' 'EL PASO'
 'VALLEDUPAR' 'LEJANÍAS' 'CUBARRAL' 'LENGUAZAQUE' 'ORTEGA' 'EL BANCO'
 'ALVARADO' 'PAUNA' 'SAN ALBERTO' 'EL PEÑÓN' 'ROVIRA' 'SAN FRANCISCO'
 'VALDIVIA' 'ARIGUANÍ (EL DIFICIL)' 'LOURDES' 'TEORAMA' 'SAN PABLO' 'PÁEZ'
 'LA DORADA' 'TIQUISIO (PUERTO RICO)' 'MONTECRISTO' 'CAPARRAPÍ' 'EBÉJICO'
 'MONTEBELLO' 'CHITA' 'BECERRILL' 'SUSA' 'SANTA FE DE ANTIOQUIA' 'CABRERA'
 'MONTENEGRO' 'MIRAFLORES' 'GRANADA' 'SAN JUAN DE ARAMA' 'SARDINATA'
 'JORDÁN' 'ARATOCA' 'ÁBREGO' 'PRADO' 'PAILITAS' nan 'OCAÑA' 'BUCARASICA'
 'GIRÓN' 'ALBANIA' 'RIO DE ORO' 'CHAPARRAL' 'LA JAGUA DEL PILAR'
 'BARRANCABERMEJA' 'LABRANZAGRANDE' 'ARMERO (GUAYABAL)' 'QUETAME'
 'SAN JACINTO DEL CAUCA' 'ASTREA' 'SANTA HELENA DEL OPÓN' 'CONTRATACIÓN'
 'OTANCHE' 'OIBA' 'PELAYA' 'CUBARÁ' 'GALÁN' 'VILLAVICENCIO' 'GÉNOVA'
 'FUNDACIÓN' 'SAN PABLO DE BORBUR' 'CÁCHIRA' 'GUAMAL' 'COLOMBIA' 'HATO'
 'TOGÜÍ' 'GUADUAS' 'CEPITÁ' 'ARBOLEDAS' 'VILLAMARIA' 'ANORÍ' 'BOGOTÁ'
 'IBAGUÉ' 'BURITICÁ' 'SEVILLA' 'AMBALEMA' 'RECETOR' 'VALLE DE SAN JUAN'
 'BARRANCAS' 'PUENTE NACIONAL' 'ANZÁ' 'FALAN' 'PIEDRAS' 'NOROSI'
 'LA PLAYA' 'PAMPLONA' 'PUERTO GAITÁN' 'CÁCERES' 'CHARTA' 'TARAZÁ'
 'PUERTO WILCHES' 'CUCUTILLA' 'MONIQUIRÁ' 'GACHALÁ' 'ZARZAL' 'REMEDIOS'
 'PLATO' 'QUINCHÍA' 'BUENAVISTA' 'ANZOÁTEGUI' 'PAYA' 'LA VICTORIA'
 'SARAVENA' 'ITUANGO' 'TONA' 'SANTA MARÍA' 'TUNUNGUÁ' 'SIMITÍ' 'SUÁREZ'
 'PIEDECUESTA' 'BARRANCO DE LOBA' 'PUERTO NARE' 'PUERTO LIBERTADOR'
 'GRAMALOTE' 'HATILLO DE LOBA' 'SANTA ROSA DEL SUR'
 'MANAURE BALCÓN DEL CESAR' 'SALDAÑA' 'BUCARAMANGA' 'HISPANIA' 'CHINÁCOTA'
 'TIBÚ' 'SAN ANTONIO' 'DUITAMA' 'SAN JUAN DE RIOSECO' 'UBALÁ' 'SAN MIGUEL'
 'JERUSALÉN' 'LA APARTADA' 'SORACÁ' 'HONDA' 'GUICÁN' 'SUSACÓN' 'SANTANA'
 'SUESCA' 'TAUSA' 'CALDAS' 'ARACATACA' 'CANTAGALLO' 'SAN DIEGO'
 'CHIQUINQUIRÁ' 'CHOACHÍ' 'GUACHETÁ' 'AGUADAS' 'SOCOTÁ' 'SANTA MARTA'
 'MORALES' 'SOCORRO' 'BETANIA' 'FÓMEQUE' 'PIJIÑO  DEL CARMEN' 'MAHATES'
 'LA JAGUA DE IBIRICO' 'LA SALINA' 'CARACOLÍ' 'GÜEPSA' 'SUPIA'
 'SAN JUAN DEL CESAR' 'SIMIJACA' 'PINILLOS' 'CARMEN DE CARUPA' 'MOGOTES'
 'NUEVA GRANADA' 'MARIPÍ' 'PEREIRA' 'SAN SEBASTIÁN DE BUENAVISTA'
 'SUBACHOQUE' 'PIVIJAY' 'MEDINA' 'CHIPATÁ' 'COROMORO' 'DOLORES'
 'SANTA BÁRBARA' 'VITERBO' 'SAMANÁ' 'YALÍ' 'EL GUACAMAYO' 'TULUÁ'
 'VILLA CARO' 'CAMPOHERMOSO' 'TAMALAMEQUE' 'TIPACOQUE' 'BRICEÑO' 'URUMITA'
 'VILLAVIEJA' 'LA VEGA' 'LOS PATIOS' 'SAN JUANITO' 'RIOVIEJO'
 'ALTOS DEL ROSARIO' 'TOLEDO' 'MACEO' 'CASTILLA LA NUEVA' 'EL MOLINO'
 'EL COCUY' 'MANZANARES' 'CARTAGO' 'CALARCÁ' 'MARIQUITA' 'SABOYÁ' 'ÚTICA'
 'PUERTO SALGAR' 'COELLO' 'FILANDIA' 'AGUAZUL' 'SUTAMARCHÁN' 'CAMPAMENTO'
 'CÓRDOBA' 'ACHÍ' 'SALAZAR' 'SAN LUIS' 'SEGOVIA' 'SAHAGÚN' 'VEGACHÍ'
 'PALESTINA' 'CHINÚ' 'PISVA' 'TINJACÁ' 'SAN GIL' 'RIOBLANCO' 'MURILLO'
 'RÁQUIRA' 'PLANETA RICA' 'CAÑASGORDAS' 'CHARALÁ' 'OLAYA' 'PEQUE'
 'LA BELLEZA' 'FORTUL' 'CHOCONTÁ' 'EL CASTILLO' 'SAN MIGUEL DE SEMA'
 'SAN CARLOS' 'HACARÍ' 'MAGANGUÉ' 'ARMENIA' 'FONSECA' 'FÚQUENE' 'EL TARRA'
 'YOPAL' 'SOATÁ' 'SABANAS DE SAN ANGEL' 'JUNÍN' 'EL CALVARIO' 'BARAYA'
 'MONTERREY' 'SAN JOSÉ DE PARE' 'VERGARA' 'SAN CAYETANO' 'ZARAGOZA' 'TAME'
 'MONGUA' 'CORRALES' 'FRESNO' 'ALGARROBO' 'APÍA' 'NEIRA' 'CONVENCIÓN'
 'TUTA' 'MUZO' 'CHAGUANÍ' 'PUEBLORRICO' 'SONSÓN' 'GACHANTIVÁ'
 'VILLA DE LEIVA' 'BARBOSA' 'SOGAMOSO' 'IZA' 'SOPETRÁN' 'LA TEBAIDA'
 'MARULANDA' 'ARANZAZU' 'PUERTO TRIUNFO' 'LÍBANO' 'PUERTO BERRÍO'
 'EL BAGRE' 'MAJAGUAL' 'SAN CALIXTO' 'CHIMA' 'PUERTO LÓPEZ' 'VIANÍ'
 'CHIPAQUE' 'MATANZA' 'GUAMO' 'MISTRATÓ' 'BELALCAZAR' 'AGUADA' 'BELTRÁN'
 'OBANDO' 'PUEBLO RICO' 'DABEIBA' 'SAN ONOFRE' 'NATAGAIMA' 'PUEBLO BELLO'
 'CURITÍ' 'RIOSUCIO' 'SABANALARGA' 'ZAPAYÁN' 'CÓMBITA' 'GUARANDA'
 'FREDONIA' 'SAN ESTANISLAO' 'CARAMANTA' 'VISTAHERMOSA' 'EL ZULIA'
 'GUADALUPE' 'PÁRAMO' 'MONGUÍ' 'LA CAPILLA' 'GAMARRA' 'TÁMARA' 'AIPE'
 'MOTAVITA' 'ANDES' 'JESÚS MARÍA' 'URAMITA' 'BITUIMA' 'GUÁTICA' 'LA MESA'
 'SAN ANDRÉS' 'VETAS' 'ABEJORRAL' 'NARIÑO' 'COPER' 'CARMEN DE VIBORAL'
 'SAN MARCOS' 'QUIPILE' 'VILLAHERMOSA' 'PIJAO' 'ONZAGA'
 'VALLE DE SAN JOSÉ' 'CERINZA' 'MARSELLA' 'SANTA ISABEL' 'TITIRIBÍ'
 'ZETAQUIRÁ' 'AMALFI' 'RESTREPO' 'TELLO' 'NEIVA' 'AQUITANIA'
 'SAN JERÓNIMO' 'SORA' 'PAIME' 'QUÍPAMA' 'VIRACACHÁ' 'GUACA' 'MUTISCUA'
 'SANTA ANA' 'PUEBLO NUEVO' 'CURUMANÍ' 'MANIZALES' 'REGIDOR' 'CUNDAY'
 'SOLEDAD' 'SAN FERNANDO' 'COYAIMA' 'SÁCHICA' 'DIBULLA' 'VENECIA'
 'LA PALMA' 'SAN VICENTE' 'ARCABUCO' 'NECHÍ' 'BUGA' 'SALENTO' 'SOCHA'
 'FLORIDABLANCA' 'CHÍQUIZA' 'CHITARAQUE' 'CHIMICHAGUA' 'ANGOSTURA'
 'GUAYABAL DE SÍQUIMA' 'JERICÓ' 'CAUCASIA' 'MOMPÓS' 'PUERTO LLERAS'
 'BOSCONIA' 'CIÉNAGA' 'CHÁMEZA' 'CAJAMARCA' 'ZAMBRANO' 'GONZÁLEZ' 'RETIRO'
 'VILLARRICA' 'COCORNÁ' 'ALBÁN' 'CONCORDIA' 'SUAITA' 'GUAPOTÁ' 'CONFINES'
 'CUMARAL' 'SANTO DOMINGO' 'SAN ZENÓN' 'PINCHOTE' 'VENTAQUEMADA'
 'LA CELIA' 'GALAPA' 'BARRANQUILLA' 'EL PIÑÓN' 'GIRARDOT' 'PAIPA' 'MANÍ'
 'LA UNIÓN' 'ANAPOIMA' 'CICUCO' 'VICTORIA' 'GARAGOA' 'LA UVITA'
 'BOCHALEMA' 'SOTAQUIRÁ' 'GÁMBITA' 'GUATAQUÍ' 'FILADELFIA' 'EL COLEGIO'
 'TAURAMENA' 'COVARACHÍA' 'VILLAPINZÓN' 'JARDÍN' 'CUCAITA' 'ANSERMA'
 'GÁMEZA' 'NORCASIA' 'MARMATO' 'CÚCUTA' 'ALPUJARRA' 'OCAMONTE'
 'EL CARMEN DE BOLÍVAR' 'TIBASOSA' 'ANSERMANUEVO' 'YARUMAL'
 'SAN LUIS DE GACENO' 'HERVEO' 'CASABIANCA' 'ENCINO' 'EL DORADO'
 'SANTA ROSA DE VITERBO' 'LABATECA' 'SINCÉ' 'SANTA BÁRBARA DE PINTO'
 'TASCO' 'ARENAL' 'LÉRIDA' 'TOLÚ' 'PALMAR' 'PAZ DE RIO' 'MARQUETALIA'
 'BELÉN' 'BELÉN DE UMBRÍA' 'BALBOA' 'APULO' 'CÁCOTA' 'MOLAGAVITA'
 'CONCEPCIÓN' 'DISTRACCIÓN' 'MEDELLÍN' 'SAN ROQUE' 'GACHETÁ' 'HERRÁN'
 'NOCAIMA' 'ANGELÓPOLIS' 'MÁLAGA' 'CERRITO' 'GUAYABETAL' 'LIBORINA'
 'HELICONIA' 'PAJARITO' 'SAN EDUARDO' 'SAN JOSE DE URE' 'PACHO' 'SALAMINA'
 'ALMEIDA' 'TENZA' 'MACARAVITA' 'QUEBRADANEGRA' 'GUACAMAYAS' 'UNE'
 'ENCISO' 'CARCASÍ' 'SAN PEDRO' 'QUIMBAYA' 'ESPINAL' 'ALCALÁ' 'CHINCHINÁ'
 'ÚMBITA' 'PENSILVANIA' 'GÓMEZ PLATA' 'MACANAL' 'ZONA BANANERA'
 'ARAUQUITA' 'LORICA' 'MONTELÍBANO' 'LA ESTRELLA' 'BERBEO' 'CALAMAR'
 'GUTIÉRREZ' 'PARATEBUENO' 'MARINILLA' 'FIRAVITOBA' 'ALEJANDRÍA' 'CHIVOR'
 'MORROA' 'VILLETA' 'COGUA' 'MAPIRIPÁN' 'SANTA ROSA DE OSOS'
 'SAN JUAN NEPOMUCENO' 'TENERIFE' 'CHIVOLO' 'GUASCA' 'SATIVASUR' 'CHISCAS'
 'GALERAS' 'FLORESTA' 'PEÑOL']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'FASES', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos:  21039
---------------
File:  Cat_sis_SGC_2021.xlsx
---------------

/tmp/ipykernel_7303/1718883424.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_SGC_2 = pd.concat([df_SGC_2, df_temp_1], ignore_index=True)

['SANTANDER' 'ANTIOQUIA' 'BOLÍVAR' 'TOLIMA' 'CESAR' 'META' 'VENEZUELA'
 'NORTE DE SANTANDER' 'BOYACÁ' 'SUCRE' 'ARAUCA' 'CALDAS' 'NORTE COLOMBIA'
 'CUNDINAMARCA' 'VALLE DEL CAUCA' 'RISARALDA' 'CASANARE' 'MAGDALENA'
 'QUINDÍO' 'HUILA' 'LA GUAJIRA' 'CÓRDOBA' 'ATLÁNTICO' 'MAR CARIBE'
 'REGIÓN FRONTERIZA']

['LOS SANTOS' 'BOLIVAR' 'CAUCASIA' 'SUCRE' 'ACHÍ' 'VILLANUEVA' 'JORDÁN'
 'CAJAMARCA' 'CANTAGALLO' 'AGUACHICA' 'SABANA DE TORRES' 'IBAGUÉ' 'GIRÓN'
 'ACACÍAS' 'MESETAS' 'PUERTO GAITÁN' 'RIONEGRO' 'RIOVIEJO' nan 'ZAPATOCA'
 'SAN VICENTE DE CHUCURÍ' 'EL PLAYÓN' 'SIMACOTA' 'PUERTO WILCHES'
 'MURILLO' 'BETULIA' 'OCAÑA' 'BARICHARA' 'CALDAS' 'COPER' 'YONDÓ (CASABE)'
 'CUBARÁ' 'SAN MARCOS' 'EL CARMEN' 'MAGANGUÉ' 'VÉLEZ' 'SARAVENA' 'TOLEDO'
 'SANTA HELENA DEL OPÓN' 'VICTORIA' 'LA ESPERANZA' 'LENGUAZAQUE' 'TIBÚ'
 'CAÑASGORDAS' 'SAN MARTIN DE LOBA' 'TARAZÁ' 'VALPARAISO'
 'BARRANCABERMEJA' 'URIBE' 'SEVILLA' 'LEBRIJA' 'SAN MARTÍN' 'PUERTO PARRA'
 'ROVIRA' 'MISTRATÓ' 'CÁCHIRA' 'ANDES' 'PUEBLO BELLO' 'PIEDECUESTA'
 'SANTA BÁRBARA' 'SOCOTÁ' 'MUZO' 'SAN ROQUE' 'SAN ALBERTO' 'VALLEDUPAR'
 'JARDÍN' 'UBATÉ' 'TÁMESIS' 'PLANADAS' 'LA PAZ' 'SOPETRÁN' 'ANSERMANUEVO'
 'RIO DE ORO' 'LA SALINA' 'PAILITAS' 'CURITÍ' 'LABATECA' 'CURUMANÍ'
 'GUADUAS' 'LA VICTORIA' 'ÁBREGO' 'CHIMICHAGUA' 'BRICEÑO' 'EL CASTILLO'
 'SAN BENITO' 'EL COPEY' 'PUERTO BOYACÁ' 'ARACATACA' 'CALARCÁ' 'AMALFI'
 'YACOPÍ' 'PUERTO SALGAR' 'CONTRATACIÓN' 'CUCUNUBÁ' 'CAMPOHERMOSO' 'PÁEZ'
 'FÚQUENE' 'FLORIÁN' 'SAN FRANCISCO' 'GALÁN' 'PAUNA' 'COLOMBIA'
 'HELICONIA' 'BETANIA' 'MARIPÍ' 'PUERTO NARE' 'MATANZA' 'RIOBLANCO'
 'CHAGUANÍ' 'ANGOSTURA' 'EL ZULIA' 'LA GLORIA' 'ARATOCA' 'ALVARADO'
 'LANDÁZURI' 'SAN VICENTE' 'CÁCERES' 'GUAVATÁ' 'REMEDIOS' 'SAN DIEGO'
 'CÚCUTA' 'VILLAMARIA' 'EL PEÑÓN' 'RIOSUCIO' 'MIRAFLORES' 'LEJANÍAS'
 'SAN PABLO DE BORBUR' 'CONVENCIÓN' 'PUERTO BERRÍO' 'JESÚS MARÍA'
 'BARBOSA' 'CASTILLA LA NUEVA' 'SABOYÁ' 'CHIPATÁ' 'ITUANGO' 'LÉRIDA'
 'CONFINES' 'BERBEO' 'SONSÓN' 'CARTAGO' 'CHIRIGUANÁ' 'AGUADA'
 'BARRANCO DE LOBA' 'PINCHOTE' 'CIMITARRA' 'OBANDO' 'SAN PABLO' 'ALBANIA'
 'FLORIDABLANCA' 'CUBARRAL' 'TAME' 'FILANDIA' 'BELALCAZAR' 'FORTUL'
 'AGUSTÍN CODAZZI' 'SIMIJACA' 'CUCAITA' 'YALÍ' 'GUAMAL' 'PIEDRAS' 'OIBA'
 'SIACHOQUE' 'CAPARRAPÍ' 'SIMITÍ' 'SALGAR' 'MORALES' 'REMOLINO' 'TOPAIPÍ'
 'QUÍPAMA' 'CHOCONTÁ' 'TÁMARA' 'LA TEBAIDA' 'PUENTE NACIONAL' 'MAJAGUAL'
 'MONTECRISTO' 'FONSECA' 'ANORÍ' 'EL CALVARIO' 'MEDINA' 'TAURAMENA'
 'TOGÜÍ' 'CEPITÁ' 'TIBASOSA' 'BUENAVISTA' 'TENERIFE' 'SAN FERNANDO' 'TONA'
 'CARMEN DE CARUPA' 'YOPAL' 'SAN BENITO ABAD' 'MARSELLA' 'ARANZAZU'
 'LA DORADA' 'TEORAMA' 'SAN CAYETANO' 'PURIFICACIÓN' 'PELAYA' 'RISARALDA'
 'SAN JUAN DE RIOSECO' 'GUATAQUÍ' 'SUESCA' 'RONCESVALLES'
 'ARIGUANÍ (EL DIFICIL)' 'NEIRA' 'GÉNOVA' 'ZARAGOZA' 'EL BAGRE'
 'LABRANZAGRANDE' 'SAMANÁ' 'NARIÑO' 'BARAYA' 'NOROSI' 'LA PLAYA'
 'SANTA ROSA DEL SUR' 'VILLAPINZÓN' 'PLANETA RICA' 'BUCARAMANGA' 'FRESNO'
 'GUACA' 'BOSCONIA' 'ZIPAQUIRÁ' 'SANTA MARTA' 'DOSQUEBRADAS' 'YOLOMBÓ'
 'SUSA' 'SANTUARIO' 'MAPIRIPÁN' 'TASCO' 'PÁCORA' 'TIQUISIO (PUERTO RICO)'
 'AMBALEMA' 'SABANAS DE SAN ANGEL' 'CABRERA' 'EL PASO' 'PUERTO TRIUNFO'
 'REPELÓN' 'QUETAME' 'GAMARRA' 'SOPLAVIENTO' 'CHITAGÁ' 'HONDA' 'HATO'
 'CIRCASIA' 'LA BELLEZA' 'GÜEPSA' 'MONIQUIRÁ' 'BUGA' 'ZAMBRANO' 'CHITA'
 'DOLORES' 'ALCALÁ' 'SAN ANDRÉS' 'SURATÁ' 'LA PALMA' 'SOCORRO' 'SAN LUIS'
 'CHIVOLO' 'CHAPARRAL' 'BECERRILL' 'MONTELÍBANO' 'DIBULLA' 'GUICÁN'
 'VENADILLO' 'SABANALARGA' 'URUMITA' 'PULÍ' 'BOAVITA' 'SALAMINA' 'ARENAL'
 'BURITICÁ' 'CONCEPCIÓN' 'FUNDACIÓN' 'UBAQUE' 'BELÉN DE UMBRÍA' 'AGUAZUL'
 'MARULANDA' 'APÍA' 'SAMACÁ' 'ARMERO (GUAYABAL)' 'LIBORINA' 'ARCABUCO'
 'UBALÁ' 'OTANCHE' 'AQUITANIA' 'LÍBANO' 'EL TARRA' 'VILLA DE LEIVA'
 'GACHALÁ' 'MARQUETALIA' 'CIÉNAGA' 'PLATO' 'SAN GIL' 'SANTA ROSA DE CABAL'
 'AYAPEL' 'MANATÍ' 'PEREIRA' 'CHIQUINQUIRÁ' 'GUASCA' 'SOGAMOSO' 'SILOS'
 'FIRAVITOBA' 'HACARÍ' 'MANZANARES' 'BARRANCAS' 'LA JAGUA DE IBIRICO'
 'EL GUACAMAYO' 'RECETOR' 'TUTAZÁ' 'PAJARITO' 'SAN JUAN DEL CESAR'
 'SUAITA' 'GACHANTIVÁ' 'SABANETA' 'SAN JUAN NEPOMUCENO' 'MEDELLÍN'
 'SAN JACINTO DEL CAUCA' 'MOGOTES' 'TAUSA' 'QUIPILE' 'SAN ANTONIO' 'VIANÍ'
 'VILLAVIEJA' 'SAN LUIS DE GACENO' 'SAN CALIXTO' 'MONGUA' 'NECHÍ'
 'VALLE DE SAN JUAN' 'FILADELFIA' 'EL BANCO' 'VALDIVIA' 'MANIZALES'
 'EL CARMEN DE BOLÍVAR' 'CHIMA' 'VEGACHÍ' 'CONCORDIA' 'PIJIÑO  DEL CARMEN'
 'CARACOLÍ' 'MONTENEGRO' 'SANTANA' 'RÁQUIRA' 'SANTA ANA' 'CAROLINA'
 'CIUDAD BOLÍVAR' 'ALPUJARRA' 'TARSO' 'VITERBO' 'PIJAO' 'NATAGAIMA'
 'FÓMEQUE' 'BALBOA' 'PRADO' 'ZETAQUIRÁ' 'PESCA' 'GÁMBITA' 'TINJACÁ'
 'SANTA MARÍA' 'ABEJORRAL' 'QUIMBAYA' 'VILLA CARO' 'RESTREPO'
 'VILLAVICENCIO' 'ANZOÁTEGUI' 'COELLO' 'MACEO' 'ARAUQUITA' 'TUNUNGUÁ'
 'MONTERREY' 'VENECIA' 'CASABIANCA' 'MARGARITA' 'TULUÁ' 'DABEIBA'
 'JERUSALÉN' 'SOCHA' 'VILLAHERMOSA' 'PUERTO LÓPEZ' 'LA ESTRELLA'
 'MOLAGAVITA' 'PUEBLORRICO' 'PAIPA' 'ALTOS DEL ROSARIO' 'SAN CARLOS'
 'SEGOVIA' 'SATIVASUR' 'FUENTE DE ORO' 'SAN JUAN DE ARAMA' 'SAN ONOFRE'
 'YARUMAL' 'PINILLOS' 'GUADALUPE' 'LA JAGUA DEL PILAR' 'PEQUE' 'SALAZAR'
 'MOMPÓS' 'SAN MIGUEL DE SEMA' 'ÚTICA' 'LA MESA' 'HISPANIA' 'ALGARROBO'
 'BELMIRA' 'CÓRDOBA' 'FOSCA' 'PUERTO LLERAS' 'SAN JOSÉ' 'SAN EDUARDO'
 'CERETÉ' 'MACANAL' 'VISTAHERMOSA' 'BELTRÁN' 'TITIRIBÍ' 'SARDINATA'
 'CHÍQUIZA' 'GRANADA' 'CAPITANEJO' 'NUEVA GRANADA' 'TOLÚ' 'REGIDOR'
 'EL ROBLE' 'FALAN' 'TAMALAMEQUE' 'PALMIRA' 'PALMAR'
 'SAN SEBASTIÁN DE BUENAVISTA' 'GUAMO' 'BELÉN' 'SUTAMARCHÁN' 'GUACHETÁ'
 'CHARTA' 'SANTA ISABEL' 'JERICÓ' 'ARBOLEDAS' 'SUPIA' 'PIVIJAY' 'AGUADAS'
 'NEIVA' 'EL COCUY' 'CHARALÁ' 'SAN JOSE DE URE' 'ANZÁ' 'CÁCOTA'
 'GUTIÉRREZ' 'ARMENIA' 'MUTISCUA' 'CARCASÍ' 'TIERRALTA' 'ATACO' 'MÁLAGA'
 'CAMPAMENTO' 'SALENTO' 'ZONA BANANERA' 'MARINILLA' 'ORTEGA' 'RONDÓN'
 'HATILLO DE LOBA' 'RETIRO' 'SAN RAFAEL' 'HERRÁN' 'OLAYA' 'ONZAGA'
 'LA MERCED' 'CHÁMEZA' 'CAICEDONIA' 'COROMORO' 'SUÁREZ' 'CHINÚ'
 'CUCUTILLA' 'CORRALES' 'SANTA ROSA DE OSOS' 'EBÉJICO' 'FREDONIA'
 'SAN MATEO' 'SUPATÁ' 'MARIQUITA' 'PAIME' 'NORCASIA' 'SAHAGÚN'
 'GUACAMAYAS' 'SAN JACINTO' 'SUBACHOQUE' 'EL PIÑÓN' 'SITIONUEVO'
 'LA APARTADA' 'CAICEDO' 'URAMITA' 'CHIVOR' 'SOATÁ' 'CHITARAQUE'
 'OCAMONTE' 'PALMAS DEL SOCORRO' 'SOTAQUIRÁ' 'CERRITO' 'BUCARASICA'
 'RIOHACHA' 'PAZ DE RIO' 'SAN JOAQUÍN' 'VALLE DE SAN JOSÉ' 'SINCÉ' 'AIPE'
 'ZAPAYÁN' 'SAN JOSÉ DE PARE' 'DON MATÍAS' 'ZARZAL' 'DUITAMA' 'SESQUILÉ'
 'DISTRACCIÓN' 'BARRANCA DE UPÍA' 'SANTA FE DE ANTIOQUIA' 'SUTATAUSA'
 'GUARANDA' 'ANAPOIMA' 'VILLARRICA' 'ENCINO' 'PUEBLO NUEVO' 'MAHATES'
 'BOCHALEMA' 'CHINÁCOTA' 'TOTA' 'NEMOCÓN' 'SINCELEJO' 'PISVA' 'CICUCO'
 'ARJONA' 'MANAURE BALCÓN DEL CESAR' 'CHIVATÁ' 'CALIFORNIA' 'APULO'
 'LAGO MARACAIBO' 'COYAIMA' 'COCORNÁ' 'COPACABANA' 'CHISCAS'
 'PUERTO LIBERTADOR' 'GIRALDO' 'GALERAS' 'TOCA' 'TALAIGUA NUEVO'
 'PAMPLONITA' 'LA CELIA' 'ALBÁN' 'MONTEBELLO' 'RAMIRIQUÍ' 'CERINZA'
 'CÁQUEZA' 'GUAYABAL DE SÍQUIMA' 'ASTREA' 'EL COLEGIO' 'MONGUÍ' 'CHOACHÍ'
 'COLOMBIA-VENEZUELA' 'SAN ZENÓN' 'SAN JOSÉ DE MIRANDA' 'PAYA' 'EL ESPINO'
 'SANTA ROSA DE VITERBO' 'SAMPUÉS' 'PARATEBUENO' 'VETAS' 'ANGELÓPOLIS'
 'SAN JERÓNIMO' 'MARÍA LA BAJA' 'BITUIMA' 'TUTA' 'TIPACOQUE' 'MOMIL'
 'PUEBLO RICO' 'TÓPAGA' 'SANTO DOMINGO' 'NOBSA' 'SAN JUANITO' 'SUSACÓN'
 'VILLETA' 'ANOLAIMA' 'ENCISO' 'SÁCHICA' 'LA CEJA' 'SASAIMA' 'PÁRAMO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'FASES', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos:  18173
---------------
File:  Cat_sis_SGC_2022.xlsx
---------------

['SANTANDER' 'ARAUCA' 'CASANARE' 'CESAR' 'ANTIOQUIA' 'CUNDINAMARCA'
 'TOLIMA' 'BOYACÁ' 'META' 'VALLE DEL CAUCA' 'HUILA' 'BOLÍVAR' 'VENEZUELA'
 'CALDAS' 'MAGDALENA' 'NORTE DE SANTANDER' 'CÓRDOBA' 'NORTE COLOMBIA'
 'LA GUAJIRA' 'SUCRE' 'QUINDÍO' 'RISARALDA' 'REGIÓN FRONTERIZA'
 'MAR CARIBE' 'ATLÁNTICO']

['LANDÁZURI' 'TAME' 'LA SALINA' 'CHIRIGUANÁ' 'CIUDAD BOLÍVAR' 'LOS SANTOS'
 'CIMITARRA' 'LENGUAZAQUE' 'VILLANUEVA' 'ZAPATOCA' 'GUAPOTÁ' 'JORDÁN'
 'HONDA' 'CURITÍ' 'SANTA HELENA DEL OPÓN' 'GIRÓN' 'VALLEDUPAR' 'EBÉJICO'
 'LABRANZAGRANDE' 'SANTA BÁRBARA' 'CHITA' 'SAN ROQUE' 'URIBE' 'AGUAZUL'
 'CARTAGO' 'PUERTO GAITÁN' 'LA GLORIA' 'BARICHARA' 'SEGOVIA' 'TAURAMENA'
 'VÉLEZ' 'PAJARITO' 'HATO' 'ARMERO (GUAYABAL)' 'PUERTO SALGAR'
 'SAN VICENTE DE CHUCURÍ' 'COLOMBIA' 'BETULIA' 'OLAYA' 'RIONEGRO'
 'SANTO DOMINGO' 'EL CARMEN' 'CABRERA' 'FORTUL' 'CAUCASIA' 'CÁCERES'
 'MEDELLÍN' 'GUAVATÁ' 'CUCUNUBÁ' 'CHAGUANÍ' 'PUERTO WILCHES'
 'SANTA ROSA DEL SUR' 'OBANDO' 'MARIQUITA' 'GUACHETÁ' 'PIEDECUESTA'
 'MACEO' 'CUBARÁ' 'BOLIVAR' nan 'SÁCAMA' 'YONDÓ (CASABE)' 'PUEBLO BELLO'
 'BELMIRA' 'MURILLO' 'SEVILLA' 'RIOBLANCO' 'SAN MARTÍN' 'PAILITAS' 'TONA'
 'PENSILVANIA' 'RONCESVALLES' 'DABEIBA' 'LA PAZ' 'MEDINA'
 'SABANA DE TORRES' 'MIRAFLORES' 'COPER' 'SIMACOTA' 'MESETAS' 'IBAGUÉ'
 'FÚQUENE' 'TUNJA' 'VILLAPINZÓN' 'ROVIRA' 'AMBALEMA' 'RIO DE ORO'
 'LEBRIJA' 'HISPANIA' 'CALIFORNIA' 'EL BANCO' 'PUERTO BERRÍO'
 'AGUSTÍN CODAZZI' 'GARAGOA' 'FUNDACIÓN' 'SABOYÁ' 'CUBARRAL' 'BUCARAMANGA'
 'LA ESPERANZA' 'ARATOCA' 'SAN PABLO' 'SAN PEDRO' 'VILLAVICENCIO' 'PULÍ'
 'PUENTE NACIONAL' 'PAUNA' 'YACOPÍ' 'TIBIRITA' 'PAIME' 'CHAPARRAL'
 'SOCORRO' 'ALVARADO' 'SAN JUANITO' 'QUÍPAMA' 'PUERTO BOYACÁ' 'TOLEDO'
 'TINJACÁ' 'GIRALDO' 'GALÁN' 'SAN JUAN DE RIOSECO' 'BELTRÁN' 'SIMIJACA'
 'GUICÁN' 'SONSÓN' 'ÁBREGO' 'CASTILLA LA NUEVA' 'NECHÍ' 'RESTREPO'
 'GUAMAL' 'SAN CAYETANO' 'CAMPOHERMOSO' 'OTANCHE' 'SOCOTÁ' 'FLORIÁN'
 'SANTA ROSA DE VITERBO' 'SABANALARGA' 'PESCA' 'TOCA' 'MONTELÍBANO'
 'EL PLAYÓN' 'TUNUNGUÁ' 'NEIVA' 'FIRAVITOBA' 'IZA' 'VEGACHÍ'
 'PLANETA RICA' 'SILOS' 'ENCINO' 'LA UVITA' 'ABEJORRAL' 'URUMITA'
 'ARCABUCO' 'CONTRATACIÓN' 'MANZANARES' 'GALERAS' 'AQUITANIA' 'CURUMANÍ'
 'EL CASTILLO' 'CHIPATÁ' 'BETANIA' 'SANTA MARTA' 'ITUANGO' 'SAN RAFAEL'
 'BELÉN' 'GUADUAS' 'VENADILLO' 'SUSACÓN' 'AGUACHICA' 'CALDAS'
 'SAN ALBERTO' 'EL PEÑÓN' 'TARAZÁ' 'ACHÍ' 'SAN SEBASTIÁN DE BUENAVISTA'
 'MATANZA' 'BARRANCO DE LOBA' 'ARROYOHONDO' 'PINILLOS' 'NATAGAIMA'
 'GACHALÁ' 'CEPITÁ' 'PISVA' 'ANDES' 'BARBOSA' 'LA BELLEZA' 'RIOVIEJO'
 'EL BAGRE' 'LA DORADA' 'SABANAS DE SAN ANGEL' 'SAMANÁ' 'EL TARRA'
 'LÍBANO' 'PÁEZ' 'MONIQUIRÁ' 'VENECIA' 'ALCALÁ' 'YOPAL' 'VICTORIA'
 'BARRANCABERMEJA' 'PINCHOTE' 'MONTERREY' 'CÓRDOBA' 'UBATÉ' 'NARIÑO'
 'GUATAQUÍ' 'BECERRILL' 'LA TEBAIDA' 'REMEDIOS' 'ARACATACA'
 'SAN PABLO DE BORBUR' 'MUTISCUA' 'VILLA DE LEIVA' 'BRICEÑO' 'ACACÍAS'
 'SAN MARCOS' 'CARACOLÍ' 'NOROSI' 'EL ZULIA' 'MUZO' 'GAMARRA' 'SUCRE'
 'PIJIÑO  DEL CARMEN' 'SAN DIEGO' 'PUEBLO NUEVO' 'GRAMALOTE' 'TOGÜÍ'
 'RECETOR' 'BALBOA' 'BUCARASICA' 'ARAUQUITA' 'SUESCA' 'CHITARAQUE'
 'ALBANIA' 'AMALFI' 'CAPARRAPÍ' 'CÁCHIRA' 'SURATÁ' 'SAN JACINTO DEL CAUCA'
 'LA PLAYA' 'CHITAGÁ' 'SAN EDUARDO' 'SOGAMOSO' 'ALTOS DEL ROSARIO'
 'MONGUA' 'COLOMBIA-VENEZUELA' 'PURIFICACIÓN' 'CARAMANTA' 'RAMIRIQUÍ'
 'BUENAVISTA' 'BARAYA' 'PIJAO' 'TIBÚ' 'SAN ANDRÉS' 'CHARALÁ' 'YALÍ'
 'GACHANTIVÁ' 'DIBULLA' 'CARMEN DE CARUPA' 'ANORÍ' 'CONCORDIA' 'SAHAGÚN'
 'MOGOTES' 'CANTAGALLO' 'SAN MARTIN DE LOBA' 'JESÚS MARÍA' 'CHIQUINQUIRÁ'
 'SARAVENA' 'PUERTO LIBERTADOR' 'SAN JOSÉ DE PARE' 'LA PALMA' 'VETAS'
 'CHÁMEZA' 'MARIPÍ' 'AIPE' 'PLANADAS' 'CHIMICHAGUA' 'SANTA ANA'
 'SAN BENITO' 'ANSERMANUEVO' 'BOAVITA' 'SAN JUAN DEL CESAR' 'OIBA'
 'FONSECA' 'TIQUISIO (PUERTO RICO)' 'PRADO' 'SANTA MARÍA' 'FLORIDABLANCA'
 'SAN MATEO' 'GUTIÉRREZ' 'QUETAME' 'CONVENCIÓN' 'AYAPEL' 'NORCASIA'
 'DOLORES' 'LEJANÍAS' 'SAN FRANCISCO' 'PUERTO PARRA' 'SALENTO' 'GÉNOVA'
 'PIEDRAS' 'SIMITÍ' 'MARQUETALIA' 'EL CALVARIO' 'SALGAR'
 'SANTA ROSA DE OSOS' 'GÁMBITA' 'CERRITO' 'BERBEO' 'SAN FERNANDO'
 'ARANZAZU' 'SUSA' 'CÁQUEZA' 'BARRANCAS' 'UBALÁ' 'LÉRIDA' 'TAMALAMEQUE'
 'CUCUTILLA' 'BOGOTÁ' 'YARUMAL' 'CAÑASGORDAS' 'MONTECRISTO' 'PAIPA'
 'TASCO' 'PAYA' 'PLATO' 'EL COPEY' 'DUITAMA' 'JUNÍN' 'NOBSA' 'DISTRACCIÓN'
 'GUAMO' 'YOLOMBÓ' 'TIBANÁ' 'JENESANO' 'VALDIVIA' 'FRESNO' 'CÁCOTA'
 'SAN ANTONIO' 'TITIRIBÍ' 'VIANÍ' 'ORTEGA' 'CHISCAS' 'MACARAVITA'
 'VITERBO' 'GONZÁLEZ' 'PELAYA' 'MONTENEGRO' 'PUEBLO RICO' 'APÍA' 'ARENAL'
 'SALAZAR' 'DOSQUEBRADAS' 'VALPARAISO' 'NUEVA GRANADA' 'MONTERÍA'
 'ZARAGOZA' 'ZAPAYÁN' 'SAN CARLOS' 'LA VICTORIA' 'TENERIFE' 'TULUÁ'
 'MORALES' 'CAICEDONIA' 'SAN JACINTO' 'SAN JOSÉ' 'SAN LUIS DE GACENO'
 'CHARTA' 'EL CARMEN DE BOLÍVAR' 'REPELÓN' 'GRANADA' 'SANTANA'
 'ALEJANDRÍA' 'OCAÑA' 'PUERTO TRIUNFO' 'CIÉNAGA' 'ANGOSTURA' 'EL COCUY'
 'MOLAGAVITA' 'PÁCORA' 'MISTRATÓ' 'BURITICÁ' 'EL MOLINO' 'SARDINATA'
 'PUEBLORRICO' 'SUAITA' 'GUATAVITA' 'QUIMBAYA' 'SAN BERNARDO'
 'SAN JUAN DE ARAMA' 'GUÁTICA' 'PIVIJAY' 'EL GUACAMAYO' 'COYAIMA'
 'BELÉN DE UMBRÍA' 'LA APARTADA' 'PALMAR' 'FALAN' 'BUSBANZÁ' 'PALESTINA'
 'RÁQUIRA' 'SAN GIL' 'RIOHACHA' 'PEQUE' 'GÁMEZA' 'TEORAMA'
 'SANTA FE DE ANTIOQUIA' 'LOS PATIOS' 'PUERTO LÓPEZ' 'SAN CALIXTO'
 'MAGANGUÉ' 'ATACO' 'BOSCONIA' 'MANAURE BALCÓN DEL CESAR' 'MARSELLA'
 'ANZOÁTEGUI' 'PEREIRA' 'CASABIANCA' 'SUTAMARCHÁN' 'SAN LUIS'
 'ANGELÓPOLIS' 'TARSO' 'CHOCONTÁ' 'MOMPÓS' 'CAMPAMENTO' 'COELLO'
 'VENTAQUEMADA' 'GÜEPSA' 'SOATÁ' 'COROMORO' 'EL GUAMO' 'TÁMESIS'
 'CONCEPCIÓN' 'ANZÁ' 'FILADELFIA' 'ARIGUANÍ (EL DIFICIL)' 'LA CELIA'
 'CÚCUTA' 'GUADALUPE' 'MAHATES' 'ZARZAL' 'CARMEN DE APICALÁ' 'TÁMARA'
 'FILANDIA' 'CUNDAY' 'GUACA' 'ANSERMA' 'LA CAPILLA' 'CHIMA'
 'VALLE DE SAN JOSÉ' 'SANTUARIO' 'CARCASÍ' 'GUAYABAL DE SÍQUIMA'
 'SAN JOSE DE URE' 'PALMAS DEL SOCORRO' 'VILLAHERMOSA' 'ARBOLEDAS'
 'VILLA CARO' 'ARMENIA' 'ALGARROBO' 'BELALCAZAR' 'CHIVOR'
 'LA JAGUA DE IBIRICO' 'JERICÓ' 'JERUSALÉN' 'CIRCASIA' 'CIÉNEGA'
 'QUINCHÍA' 'CHINÚ' 'SUPIA' 'MANIZALES' 'MACANAL' 'TOPAIPÍ' 'CERINZA'
 'SAN JOAQUÍN' 'LA VIRGINIA' 'ASTREA' 'VILLAVIEJA' 'CALARCÁ' 'GUATAPÉ'
 'AGUADA' 'BELLO' 'EL PASO' 'HATILLO DE LOBA' 'CHOACHÍ'
 'SANTA ROSA DE CABAL' 'SOPETRÁN' 'CAJAMARCA' 'COCORNÁ' 'VERGARA'
 'SALAMINA' 'AGUADAS' 'ÚTICA' 'TAUSA' 'CHINCHINÁ' 'SÁCHICA' 'TELLO'
 'VILLAMARIA' 'ZETAQUIRÁ' 'SANTA SOFÍA' 'SAMPUÉS' 'AMAGÁ' 'RIOSUCIO'
 'SAN MIGUEL DE SEMA' 'PÁRAMO' 'NEIRA' 'OCAMONTE' 'LIBORINA'
 'SAN BENITO ABAD' 'CÓMBITA' 'MACHETÁ' 'PACHO' 'SAN LUIS DE PALENQUE'
 'LA MERCED' 'QUEBRADANEGRA' 'BUGA' 'HACARÍ' 'ULLOA' 'NUNCHÍA'
 'ZONA BANANERA' 'CIÉNAGA DE ORO' 'SANTA BÁRBARA DE PINTO' 'FÓMEQUE'
 'SANTA ISABEL' 'SUTATENZA' 'FLORESTA' 'ZAMBRANO' 'PALOCABILDO'
 'CHINAVITA' 'PARATEBUENO' 'PANQUEBA' 'PALMAR DE VARELA' 'SILVANIA'
 'URAMITA' 'SITIONUEVO' 'SUBACHOQUE' 'LOS PALMITOS' 'SOTAQUIRÁ'
 'SAN JUAN NEPOMUCENO' 'LABATECA' 'LA JAGUA DEL PILAR' 'QUIPILE'
 'CERRO DE SAN ANTONIO' 'ANOLAIMA' 'PEÑOL' 'JARDÍN' 'RETIRO' 'ESPINAL'
 'SAMACÁ' 'SAN JOSÉ DE MIRANDA' 'CUÍTIVA' 'PUERTO NARE' 'TUTA' 'ONZAGA'
 'LAGO MARACAIBO' 'PALMITO' 'DURANIA' 'COGUA' 'REGIDOR' 'SALDAÑA'
 'CARMEN DE VIBORAL' 'MONGUÍ' 'DON MATÍAS' 'SAN JOSÉ DE LA MONTAÑA'
 'ALPUJARRA' 'UNE' 'VISTAHERMOSA' 'BITUIMA' 'PAMPLONA' 'PACHAVITA'
 'VALLE DE SAN JUAN' 'GÓMEZ PLATA' 'PAZ DE RIO' 'SAN VICENTE' 'BOJACÁ']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'FASES', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio'],
      dtype='object')
Eventos:  16962
---------------
File:  Cat_sis_SGC_2019.xlsx
---------------

['BOYACÁ' 'MAGDALENA' 'CESAR' 'SANTANDER' 'NORTE DE SANTANDER'
 'CUNDINAMARCA' 'ANTIOQUIA' 'HUILA' 'BOLÍVAR' 'VALLE DEL CAUCA' 'TOLIMA'
 'CASANARE' 'META' 'RISARALDA' 'ARAUCA' 'CALDAS' 'VENEZUELA' 'LA GUAJIRA'
 'ATLÁNTICO' 'QUINDÍO' 'NORTE COLOMBIA' 'CÓRDOBA' 'NORTHERN COLOMBIA'
 'SUCRE' 'ÁREA DE INFLUENCIA VOLCÁN NEVADO DEL HUILA'
 'AREA DE INFLUENCIA VOLCÁN NEVADO DEL HUILA' 'SAN ANDRÉS PROVIDENCIA'
 'MAR CARIBE']

['SANTA MARÍA' 'GUAMAL' 'CURUMANÍ' 'LOS SANTOS' 'RIONEGRO' 'SALAZAR'
 'LEBRIJA' 'GONZÁLEZ' 'LA JAGUA DE IBIRICO' 'CUCUNUBÁ' 'BOLIVAR'
 'EL BAGRE' 'GIRÓN' 'BARAYA' 'BUCARAMANGA' 'SABANA DE TORRES' 'ZAPATOCA'
 'MONTECRISTO' 'SIMITÍ' 'GALÁN' 'YONDÓ (CASABE)' 'EL CARMEN' 'PELAYA'
 'MORALES' 'SANTA ROSA DEL SUR' 'CÁCERES' 'CARTAGO' 'CHIRIGUANÁ'
 'MOTAVITA' 'VILLANUEVA' 'FÚQUENE' 'LANDÁZURI' 'SANTA ISABEL' 'MARIPÍ'
 'CÁCHIRA' 'LA ESPERANZA' 'TÁMARA' 'CHITA' 'YACOPÍ' 'SUCRE'
 'SAN VICENTE DE CHUCURÍ' 'EL PLAYÓN' 'RONCESVALLES' 'BETULIA' 'TOLEDO'
 'CIÉNAGA' 'CHAPARRAL' 'SUSA' 'SAN EDUARDO' 'ALVARADO' 'CUBARRAL'
 'PAILITAS' 'LEJANÍAS' 'PLANADAS' 'NOROSI' 'LA GLORIA' 'AGUSTÍN CODAZZI'
 'ORTEGA' 'SANTUARIO' 'RIO DE ORO' 'RIOVIEJO' 'SAN MARTÍN' 'SIMACOTA'
 'ARENAL' 'SANTA HELENA DEL OPÓN' 'SEVILLA' 'SABOYÁ' 'SARAVENA' 'PÁEZ'
 'VIANÍ' 'CANTAGALLO' 'PULÍ' 'URIBE' 'BOSCONIA' 'PIEDECUESTA' 'BARICHARA'
 'PUERTO BOYACÁ' 'LA PAZ' 'EL PEÑÓN' 'LENGUAZAQUE' 'ARATOCA' 'GUADUAS'
 'ÁBREGO' 'SAN PABLO' 'OCAÑA' 'SAN SEBASTIÁN DE BUENAVISTA' 'ACACÍAS'
 'CONCEPCIÓN' 'CIMITARRA' 'PUENTE NACIONAL' 'HATO' 'CHIMA' 'SANTANA'
 'VÉLEZ' 'CONVENCIÓN' 'FUNDACIÓN' 'GUAYATÁ' 'SANTA ANA' 'CONTRATACIÓN'
 'MAGANGUÉ' 'COLOMBIA' 'AGUACHICA' 'GÜEPSA' 'TIQUISIO (PUERTO RICO)'
 'NATAGAIMA' 'CHIPATÁ' 'NECHÍ' 'LABRANZAGRANDE' 'PAJARITO' 'OTANCHE'
 'SAN PABLO DE BORBUR' 'SURATÁ' 'PAUNA' 'PIVIJAY' 'TARAZÁ' 'MARULANDA'
 'CUBARÁ' 'MUZO' 'SIMIJACA' 'PISVA' 'MOLAGAVITA' nan 'DIBULLA' 'JORDÁN'
 'VALLEDUPAR' 'VILLAHERMOSA' 'SANTA BÁRBARA' 'EL BANCO' 'SANTA MARTA'
 'BELÉN DE UMBRÍA' 'CIUDAD BOLÍVAR' 'SAN ALBERTO' 'ANDES' 'PURIFICACIÓN'
 'PUERTO WILCHES' 'LA BELLEZA' 'REMEDIOS' 'SAN ANTONIO'
 'SANTA ROSA DE OSOS' 'ABEJORRAL' 'VILLAMARIA' 'PUERTO PARRA' 'TEORAMA'
 'MALAMBO' 'GALAPA' 'YOLOMBÓ' 'CASTILLA LA NUEVA' 'TAME' 'CABRERA'
 'CHITAGÁ' 'SOCORRO' 'VENECIA' 'BARRANCO DE LOBA' 'ZARZAL' 'TIBÚ'
 'VILLAVIEJA' 'PUERTO GAITÁN' 'NORCASIA' 'ARMENIA' 'GUAVATÁ' 'ALBANIA'
 'MACEO' 'BARRANCABERMEJA' 'EL GUACAMAYO' 'MONIQUIRÁ' 'REGIDOR'
 'PUERTO LLERAS' 'SOGAMOSO' 'CAJAMARCA' 'PUERTO BERRÍO' 'BOGOTÁ'
 'ALGARROBO' 'BRICEÑO' 'PUEBLO BELLO' 'EL COPEY' 'BELTRÁN' 'OBANDO'
 'AMBALEMA' 'LA VICTORIA' 'COPER' 'CALARCÁ' 'SAN CALIXTO' 'PINILLOS'
 'CAPARRAPÍ' 'LA APARTADA' 'SOCOTÁ' 'MATANZA' 'CHIMICHAGUA' 'SABANALARGA'
 'SAN FRANCISCO' 'EL CASTILLO' 'TASCO' 'TINJACÁ' 'ROVIRA'
 'SAN MARTIN DE LOBA' 'CHAGUANÍ' 'GUICÁN' 'QUIPILE' 'FOSCA' 'CASABIANCA'
 'MURILLO' 'MESETAS' 'NEIVA' 'SAN JUANITO' 'ARIGUANÍ (EL DIFICIL)'
 'BUENAVISTA' 'AQUITANIA' 'BECERRILL' 'SAN JOSÉ DE PARE' 'CAMPOHERMOSO'
 'SANTA FE DE ANTIOQUIA' 'VENADILLO' 'SAN CARLOS' 'BETANIA' 'AYAPEL'
 'MISTRATÓ' 'GUAMO' 'MAJAGUAL' 'MEDINA' 'MIRAFLORES' 'PRADO' 'QUIMBAYA'
 'VALDIVIA' 'BUGALAGRANDE' 'GAMARRA' 'EL PIÑÓN' 'SEGOVIA' 'LA PALMA'
 'HISPANIA' 'TOPAIPÍ' 'TAMALAMEQUE' 'HONDA' 'MONTERREY' 'LA DORADA'
 'LIBORINA' 'GUADALUPE' 'CUCUTILLA' 'ARMERO (GUAYABAL)' 'ANORÍ' 'RECETOR'
 'CEPITÁ' 'CONCORDIA' 'RIOBLANCO' 'ARBOLEDAS' 'SUESCA' 'MANATÍ' 'DOLORES'
 'CALDAS' 'GÁMBITA' 'JESÚS MARÍA' 'OLAYA' 'EBÉJICO' 'TAUSA' 'IBAGUÉ'
 'ITUANGO' 'ZARAGOZA' 'CARMEN DE VIBORAL' 'SILOS' 'EL CALVARIO'
 'SAN CAYETANO' 'ANZOÁTEGUI' 'SONSÓN' 'EL ZULIA' 'PIEDRAS' 'UBATÉ'
 'ONZAGA' 'VISTAHERMOSA' 'LA SALINA' 'FLORIÁN' 'SARDINATA' 'MONTENEGRO'
 'MONGUÍ' 'MONGUA' 'ARACATACA' 'LA MERCED' 'CAÑASGORDAS' 'CÓRDOBA'
 'CHARTA' 'LA PLAYA' 'URUMITA' 'PÁCORA' 'GUACHETÁ' 'CARMEN DE CARUPA'
 'CÁCOTA' 'TOTA' 'YOPAL' 'TUNUNGUÁ' 'BELMIRA' 'BARBOSA' 'CHINAVITA'
 'VALLE DE SAN JUAN' 'CAUCASIA' 'AGUADA' 'VILLA CARO' 'CARAMANTA' 'HACARÍ'
 'TIBASOSA' 'ZONA BANANERA' 'SAN JOSE DE URE' 'SAN DIEGO' 'REMOLINO'
 'PLATO' 'TENERIFE' 'ARANZAZU' 'SOPLAVIENTO' 'SAN LUIS' 'MARSELLA'
 'SUAITA' 'GÉNOVA' 'CHARALÁ' 'RESTREPO' 'MARÍA LA BAJA' 'ANAPOIMA'
 'CURITÍ' 'CHIQUINQUIRÁ' 'ZAPAYÁN' 'COROMORO' 'RIOHACHA' 'FILADELFIA'
 'SAN JUAN DEL CESAR' 'MARGARITA' 'YARUMAL' 'VICTORIA' 'PINCHOTE' 'TULUÁ'
 'SALENTO' 'SUTAMARCHÁN' 'EL PASO' 'ALPUJARRA' 'CHISCAS' 'CHÍQUIZA'
 'SAN ANDRÉS' 'MANIZALES' 'SÁCAMA' 'SALDAÑA' 'SAN JUAN DE RIOSECO'
 'PEREIRA' 'GARAGOA' 'MANAURE BALCÓN DEL CESAR' 'CARCASÍ' 'MACANAL'
 'ANSERMA' 'UBALÁ' 'CAICEDONIA' 'LA CAPILLA' 'ÚMBITA' 'QUETAME' 'CHIVOR'
 'EL MOLINO' 'SAN LUIS DE GACENO' 'SAN GIL' 'BARRANQUILLA' 'MARIQUITA'
 'SAN MARCOS' 'FORTUL' 'EL COCUY' 'MAHATES' 'EL TARRA' 'CERRITO' 'SAMACÁ'
 'AMALFI' 'MUTISCUA' 'SAN FERNANDO' 'GACHALÁ' 'ARAUQUITA' 'CONFINES'

In [ ]:
df_SGC_2['Catalogo'] = 'SGC 2'
df_SGC_2['Gap'] = df_SGC_2['Gap'].astype(float)
df_SGC_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134030 entries, 0 to 134029
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fecha-Hora UTC          134030 non-null  object
 1   Latitud                 134030 non-null  float64
 2   Longitud                134030 non-null  float64
 3   Profundidad [km]        134030 non-null  float64
 4   Magnitud                134030 non-null  float64
 5   Tipo Magnitud           134030 non-null  object
 6   Error Latitud [km]      134030 non-null  float64
 7   Error Longitud [km]     134030 non-null  float64
 8   Error Profundidad [km]  134030 non-null  float64
 9   Numero de Fases         134030 non-null  object
 10  RMS [seg]               134030 non-null  float64
 11  Gap                     134030 non-null  float64
 12  Departamento            134030 non-null  object
 13  Municipio               132275 non-null  object
 14  Catalogo                134030 non-null  object
dtypes: float64(9), object(6)
memory usage: 15.3+ MB

In [ ]:
df_SGC_2.head()

,Fecha-Hora UTC,Latitud,Longitud,Profundidad [km],Magnitud,Tipo Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],Numero de Fases,RMS [seg],Gap,Departamento,Municipio,Catalogo
0,2020-01-01 00:12:05,7.431,-73.228,132.82,1.4,MLr_vmm,1.344,1.344,1.8,21,0.3,106.0,SANTANDER,RIONEGRO,SGC 2
1,2020-01-01 00:13:16,6.792,-73.157,148.48,1.8,MLr_3,1.556,1.556,2.1,20,0.4,136.0,SANTANDER,LOS SANTOS,SGC 2
2,2020-01-01 00:14:37,6.848,-73.191,141.49,1.5,MLr_3,2.333,2.333,4.7,7,0.3,129.0,SANTANDER,ZAPATOCA,SGC 2
3,2020-01-01 00:16:17,6.829,-73.183,142.00,1.5,MLr_3,1.909,1.909,3.9,11,0.4,130.0,SANTANDER,ZAPATOCA,SGC 2
4,2020-01-01 00:40:18,3.136,-74.496,23.61,1.0,MLr_3,3.465,3.465,1.9,8,0.3,279.0,META,URIBE,SGC 2

## Catalogo TECTO

In [ ]:
path_catalogo = os.path.join(path_datasets, 'Cat_sis_SGC_TECTO_feb2014_2024')
os.listdir(path_catalogo)

df_SGC_TECTO = df_general.copy()

for i in os.listdir(path_catalogo)[:]:
  if i.endswith('.xlsx') and (i != 'excel_estaciones.xlsx'):
    print('-----'*3)
    print('File: ', i)
    print('-----'*3)
    df_temp_1 = sup.io.crear_catalogo_SGC_TECTO(path_catalogo=path_catalogo,
                                                file_excel=i)

    print(df_temp_1.shape)
    df_SGC_TECTO = pd.concat([df_SGC_TECTO, df_temp_1], ignore_index=True)
    df_SGC_TECTO.reset_index(drop=True, inplace=True)

    del df_temp_1

---------------
File:  Cat_sis_SGC_TECTO_2017.xlsx
---------------

['BOLÍVAR' 'ANTIOQUIA' 'NORTE DE SANTANDER' 'SANTANDER' 'MAGDALENA'
 'CESAR' 'BOYACÁ' 'ZULIA' 'CALDAS']

['NOROSÍ' 'PUERTO NARE' 'CÁCHIRA' 'LA PAZ' 'PUERTO WILCHES' 'RIONEGRO'
 'LA BELLEZA' 'ARIGUANÍ (EL DIFÍCIL)' 'TIQUISIO (PUERTO RICO)' 'PELAYA'
 'MONTECRISTO' 'BECERRIL' 'OTANCHE' 'AGUSTÍN CODAZZI' 'PUERTO PARRA'
 'PAILITAS' 'CIMITARRA' 'SABANA DE TORRES' 'LEBRIJA' 'YONDÓ (CASABE)'
 'EL CARMEN' 'LA JAGUA DE IBIRICO' 'SAN LUIS' 'MANAURE BALCÓN DEL CESAR'
 'PUERTO BERRÍO' 'CHIMICHAGUA' 'HATO' 'EL PLAYÓN' 'CURUMANÍ' 'EL BAGRE'
 'MACEO' 'EL PEÑÓN' 'REMEDIOS' 'SIMACOTA' 'SAN PABLO' 'SANTA ROSA DEL SUR'
 'EL PASO' 'ASTREA' 'BARRANCABERMEJA' 'ALGARROBO' 'CONVENCIÓN'
 'CHIRIGUANÁ' 'ZAPATOCA' 'GAMARRA' 'BETULIA' 'SIMITÍ' 'CANTAGALLO'
 'LANDÁZURI' 'CARACOLÍ' 'SAN MARTÍN' 'ALTOS DEL ROSARIO' 'AGUACHICA'
 'SABANAS DE SAN ÁNGEL' 'PUEBLO BELLO' 'SEGOVIA' 'PUERTO BOYACÁ'
 'BOSCONIA' 'EL COPEY' 'SANTA HELENA DEL OPÓN' 'MACHIQUES' 'OCAÑA'
 'TAMALAMEQUE' 'PUERTO TRIUNFO' 'MATANZA' 'SAN VICENTE DE CHUCURÍ'
 'GUAMAL' 'HATILLO DE LOBA' 'EL TARRA' 'HACARÍ' 'EL BANCO' 'CONTRATACIÓN'
 'SAN MARTÍN DE LOBA' 'LA ESPERANZA' 'ARENAL' 'PINILLOS' 'VEGACHÍ'
 'NORCASIA' 'SAN ALBERTO' 'GALÁN' 'MARGARITA' 'SUCRE' 'VALLEDUPAR'
 'BARRANCO DE LOBA' 'YALÍ' 'ÁBREGO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  1119
(1119, 14)
---------------
File:  Cat_sis_SGC_TECTO_2016.xlsx
---------------

['BOLÍVAR' 'ANTIOQUIA' 'CESAR' 'MAGDALENA' 'SANTANDER'
 'NORTE DE SANTANDER' 'BOYACÁ' 'ZULIA' 'CUNDINAMARCA' 'CALDAS']

['NOROSÍ' 'REMEDIOS' 'CURUMANÍ' 'LA JAGUA DE IBIRICO' 'ALTOS DEL ROSARIO'
 'MONTECRISTO' 'PELAYA' 'SAN LUIS' 'EL BANCO' 'EL PEÑÓN' 'BECERRIL'
 'GUAMAL' 'GAMARRA' 'PAILITAS' 'VEGACHÍ' 'CHIRIGUANÁ' 'OCAÑA'
 'HATILLO DE LOBA' 'TIQUISIO (PUERTO RICO)' 'SAN MARTÍN DE LOBA' 'OTANCHE'
 'PUERTO BERRÍO' 'CONTRATACIÓN' 'MANAURE BALCÓN DEL CESAR'
 'BARRANCABERMEJA' 'MACHIQUES' 'SANTA ROSA DEL SUR' 'PUERTO TRIUNFO'
 'CANTAGALLO' 'SIMITÍ' 'LA ESPERANZA' 'ÁBREGO' 'PUERTO PARRA' 'CÁCHIRA'
 'AGUSTÍN CODAZZI' 'ALGARROBO' 'PUERTO SALGAR' 'MORALES'
 'SABANAS DE SAN ÁNGEL' 'YONDÓ (CASABE)' 'SEGOVIA' 'LA BELLEZA' 'RIONEGRO'
 'SANTA HELENA DEL OPÓN' 'EL CARMEN' 'PIEDECUESTA' 'PUERTO NARE'
 'JESÚS MARÍA' 'PUERTO WILCHES' 'BARRANCO DE LOBA' 'CARACOLÍ' 'ASTREA'
 'EL PLAYÓN' 'MACEO' 'LEBRIJA' 'CIMITARRA' 'SAN MARTÍN' 'LA GLORIA'
 'EL PASO' 'BUCARAMANGA' 'SAN PABLO' 'SABANA DE TORRES'
 'SAN VICENTE DE CHUCURÍ' 'SIMACOTA' 'BOSCONIA' 'AGUACHICA' 'PAUNA'
 'LA PLAYA' 'VALLEDUPAR' 'HATO' 'PUERTO BOYACÁ' 'ARENAL' 'EL TARRA'
 'PINILLOS' 'REGIDOR' 'LA DORADA' 'CAPARRAPÍ' 'EL COPEY' 'LA PAZ'
 'SAN FRANCISCO' 'PUEBLO BELLO' 'MATANZA' 'GUAVATÁ' 'FLORIÁN'
 'SAN ALBERTO' 'GALÁN' 'SAN CARLOS' 'BETULIA' 'SAN DIEGO' 'EL BAGRE'
 'TAMALAMEQUE' 'CHIMICHAGUA' 'YACOPÍ' 'VILLA CARO' 'ZAPATOCA' 'SURATÁ'
 'GONZÁLEZ' 'SAN FERNANDO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  1056
(1056, 14)
---------------
File:  Cat_sis_SGC_TECTO_2015.xlsx
---------------

['BOLÍVAR' 'SANTANDER' 'ANTIOQUIA' 'CESAR' 'NORTE DE SANTANDER'
 'MAGDALENA' 'BOYACÁ' 'ZULIA' 'SUCRE']

['SAN PABLO' 'TIQUISIO (PUERTO RICO)' 'EL CARMEN' 'YONDÓ (CASABE)'
 'PUERTO BERRÍO' 'SAN ALBERTO' 'LEBRIJA' 'RIONEGRO' 'CANTAGALLO'
 'PUERTO PARRA' 'LA ESPERANZA' 'HACARÍ' 'RÍO DE ORO' 'PELAYA'
 'SANTA ROSA DEL SUR' 'SIMITÍ' 'PUERTO WILCHES' 'BARICHARA' 'EL PLAYÓN'
 'NOROSÍ' 'SAN VICENTE DE CHUCURÍ' 'SABANA DE TORRES' 'MONTECRISTO'
 'SAN MARTÍN' 'GUAMAL' 'OCAÑA' 'BARRANCABERMEJA' 'AGUACHICA'
 'ALTOS DEL ROSARIO' 'HATILLO DE LOBA' 'ARENAL' 'REMEDIOS' 'TAMALAMEQUE'
 'SEGOVIA' 'CURUMANÍ' 'PAILITAS' 'EL PEÑÓN' 'SAN MARTÍN DE LOBA'
 'ZAPATOCA' 'GAMARRA' 'VEGACHÍ' 'CARACOLÍ' 'REGIDOR' 'GALÁN'
 'SANTA HELENA DEL OPÓN' 'LA GLORIA' 'MORALES' 'CIMITARRA' 'OTANCHE'
 'PUERTO BOYACÁ' 'SAN FRANCISCO' 'BARRANCO DE LOBA' 'EL BAGRE' 'CONFINES'
 'PALMAS DEL SOCORRO' 'MACEO' 'PUERTO NARE' 'ÁBREGO' 'CHIMICHAGUA'
 'LANDÁZURI' 'MARGARITA' 'FLORIDABLANCA' 'CONVENCIÓN' 'EL BANCO'
 'LA PLAYA' 'VILLA CARO' 'EL TARRA' 'CONTRATACIÓN' 'LA BELLEZA'
 'BUCARASICA' 'SAN LUIS' 'AGUSTÍN CODAZZI' 'BOSCONIA' 'ALGARROBO'
 'CHIRIGUANÁ' 'MACHIQUES' 'EL PASO' 'LA JAGUA DE IBIRICO' 'BECERRIL'
 'MANAURE BALCÓN DEL CESAR' 'SABANAS DE SAN ÁNGEL' 'CÁCHIRA' 'LOS SANTOS'
 'GUARANDA']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  803
(803, 14)
---------------
File:  Cat_sis_SGC_TECTO_2014.xlsx
---------------

['ANTIOQUIA' 'CUNDINAMARCA' 'CESAR' 'BOLÍVAR' 'NORTE DE SANTANDER'
 'SANTANDER' 'MAGDALENA']

['YONDÓ (CASABE)' 'PUERTO SALGAR' 'TAMALAMEQUE' 'NOROSÍ' 'HATILLO DE LOBA'
 'BARRANCO DE LOBA' 'SAN PABLO' 'SIMITÍ' 'REMEDIOS' 'ALTOS DEL ROSARIO'
 'CÁCHIRA' 'SANTA ROSA DEL SUR' 'EL CARMEN' 'PUERTO WILCHES'
 'TIQUISIO (PUERTO RICO)' 'LANDÁZURI' 'MONTECRISTO' 'SAN MARTÍN'
 'SAN ALBERTO' 'LEBRIJA' 'CANTAGALLO' 'PUERTO BERRÍO'
 'SAN VICENTE DE CHUCURÍ' 'PUERTO PARRA' 'SABANA DE TORRES' 'PELAYA'
 'RÍO VIEJO' 'PAILITAS' 'GAMARRA' 'CURUMANÍ' 'EL BANCO' 'LA GLORIA'
 'SEGOVIA' 'EL PEÑÓN' 'LA ESPERANZA' 'CHIMICHAGUA' 'MORALES' 'EL PLAYÓN'
 'VILLA CARO' 'ÁBREGO' 'OCAÑA' 'EL TARRA' 'EL BAGRE' 'SURATÁ' 'LA PLAYA'
 'HACARÍ' 'SAN MARTÍN DE LOBA' 'BARRANCABERMEJA' 'MARGARITA' 'ACHÍ'
 'GALÁN' 'AGUACHICA' 'ARENAL' 'GUAMAL' 'GONZÁLEZ' 'PINILLOS' 'RIONEGRO'
 'REGIDOR' 'NECHÍ' 'SANTA HELENA DEL OPÓN']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  595
(595, 14)
---------------
File:  Cat_sis_SGC_TECTO_2018.xlsx
---------------

/tmp/ipykernel_7303/343974462.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_SGC_TECTO = pd.concat([df_SGC_TECTO, df_temp_1], ignore_index=True)

['CESAR' 'SANTANDER' 'BOYACÁ' 'BOLÍVAR' 'NORTE DE SANTANDER' 'ANTIOQUIA'
 'MAGDALENA']

['LA GLORIA' 'CURUMANÍ' 'CIMITARRA' 'OTANCHE' 'LA PAZ' 'NOROSI' 'RIOVIEJO'
 'EL PASO' 'EL PEÑÓN' 'EL CARMEN' 'SAN PABLO' 'SABANA DE TORRES'
 'CANTAGALLO' 'ÁBREGO' 'LA BELLEZA' 'PUERTO BERRÍO' 'EL BANCO'
 'YONDÓ (CASABE)' 'CHIMICHAGUA' 'RIONEGRO' 'PAILITAS'
 'LA JAGUA DE IBIRICO' 'MORALES' 'REMEDIOS' 'SANTA HELENA DEL OPÓN'
 'SAN VICENTE DE CHUCURÍ' 'SAN ALBERTO' 'BARRANCABERMEJA' 'PUERTO WILCHES'
 'SAN FRANCISCO' 'BETULIA' 'PUERTO PARRA' 'ZAPATOCA' 'SONSÓN' 'CÁCHIRA'
 'LEBRIJA' 'LA ESPERANZA' 'PUERTO BOYACÁ' 'BOLIVAR' 'LANDÁZURI'
 'BECERRILL' 'PELAYA' 'SANTA ROSA DEL SUR' 'SIMITÍ' 'VEGACHÍ' 'SIMACOTA'
 'AGUSTÍN CODAZZI' 'CHIRIGUANÁ' 'GIRÓN' 'AGUACHICA' 'MACEO' 'TAMALAMEQUE'
 'VALLEDUPAR' 'SAN LUIS' 'SAN MARTIN DE LOBA' 'BOSCONIA'
 'ALTOS DEL ROSARIO' 'ARENAL' 'SUCRE' 'BARRANCO DE LOBA' 'YALÍ' 'CARACOLÍ'
 'GALÁN' 'GAMARRA' 'OCAÑA' 'PUERTO TRIUNFO' 'CONTRATACIÓN' 'YOLOMBÓ'
 'SAN MARTÍN' 'VÉLEZ' 'FLORIÁN' 'REGIDOR' 'SAN CARLOS' 'HATILLO DE LOBA'
 'TIQUISIO (PUERTO RICO)' 'RIO DE ORO' 'CHIMA' 'PUERTO NARE']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  809
(809, 14)
---------------
File:  Cat_sis_SGC_TECTO_2020.xlsx
---------------

['BOLÍVAR' 'SANTANDER' 'ANTIOQUIA' 'NORTE DE SANTANDER' 'CESAR' 'BOYACÁ'
 'MAGDALENA']

['SAN MARTIN DE LOBA' 'PUERTO PARRA' 'RIONEGRO' 'YONDÓ (CASABE)'
 'SIMACOTA' 'SAN PABLO' 'OCAÑA' 'EL CARMEN' 'CIMITARRA' 'LA PAZ'
 'VALLEDUPAR' 'PUERTO WILCHES' 'REMEDIOS' 'PUERTO NARE' 'PUERTO BOYACÁ'
 'HATILLO DE LOBA' 'AGUSTÍN CODAZZI' 'GIRÓN' 'BOLIVAR' 'LEBRIJA'
 'CANTAGALLO' 'BARRANCABERMEJA' 'CARACOLÍ' 'SABANA DE TORRES'
 'LA ESPERANZA' 'EL PEÑÓN' 'SUCRE' 'LA GLORIA' 'LA BELLEZA' 'CÁCHIRA'
 'SAN FRANCISCO' 'LANDÁZURI' 'PUERTO TRIUNFO' 'PUERTO BERRÍO'
 'SAN VICENTE DE CHUCURÍ' 'SAN LUIS' 'PAILITAS' 'SAN ALBERTO' 'OTANCHE'
 'SIMITÍ' 'CHIRIGUANÁ' 'CHIMA' 'VÉLEZ' 'NOROSI' 'MACEO' 'BECERRILL'
 'SONSÓN' 'EL PLAYÓN' 'SAN CARLOS' 'EL PASO' 'SANTA HELENA DEL OPÓN'
 'LA JAGUA DE IBIRICO' 'SANTA ROSA DEL SUR' 'GAMARRA' 'ZAPATOCA'
 'BARRANCO DE LOBA' 'EL GUACAMAYO' 'VEGACHÍ' 'PELAYA' 'CHIMICHAGUA'
 'BETULIA' 'EL BANCO' 'ARENAL' 'CURUMANÍ' 'MORALES' 'SAN MARTÍN'
 'TAMALAMEQUE' 'BOSCONIA' 'YOLOMBÓ' 'RIOVIEJO' 'RIO DE ORO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  592
(592, 14)
---------------
File:  Cat_sis_SGC_TECTO_2024.xlsx
---------------

['SANTANDER' 'CESAR' 'ANTIOQUIA' 'BOLÍVAR' 'NORTE DE SANTANDER']

['LANDÁZURI' 'CHIMICHAGUA' 'CIMITARRA' 'SAN CARLOS' 'BOLIVAR'
 'BARRANCABERMEJA' 'YONDÓ (CASABE)' 'SABANA DE TORRES' 'CANTAGALLO'
 'LA GLORIA' 'SAN PABLO' 'PUERTO WILCHES' 'PUERTO PARRA' 'EL CARMEN'
 'REMEDIOS' 'HATO' 'PUERTO NARE' 'YOLOMBÓ' 'LA ESPERANZA' 'SIMITÍ' 'SUCRE'
 'PUERTO BERRÍO' 'SIMACOTA' 'EL PEÑÓN' 'GIRÓN' 'ALTOS DEL ROSARIO'
 'SAN FRANCISCO' 'RIONEGRO' 'PELAYA' 'ÁBREGO' 'MACEO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  88
(88, 14)
---------------
File:  Cat_sis_SGC_TECTO_2023.xlsx
---------------

['SANTANDER' 'CESAR' 'BOLÍVAR' 'ANTIOQUIA' 'BOYACÁ' 'NORTE DE SANTANDER'
 'MAGDALENA' 'CUNDINAMARCA']

['EL CARMEN' 'BUCARAMANGA' 'AGUACHICA' 'SAN PABLO' 'YONDÓ (CASABE)'
 'CARACOLÍ' 'SAN LUIS' 'SAN FRANCISCO' 'YALÍ' 'CIMITARRA' 'PELAYA'
 'SIMACOTA' 'BARRANCABERMEJA' 'CANTAGALLO' 'PUERTO BOYACÁ' 'LA ESPERANZA'
 'LANDÁZURI' 'BOLIVAR' 'MACEO' 'EL PLAYÓN' 'PUERTO PARRA' 'PUERTO BERRÍO'
 'SONSÓN' 'BETULIA' 'GIRÓN' 'SANTA ROSA DEL SUR' 'SAN MARTIN DE LOBA'
 'OTANCHE' 'SAN MARTÍN' 'REMEDIOS' 'LA BELLEZA' 'LEBRIJA' 'PUERTO WILCHES'
 'ALTOS DEL ROSARIO' 'RIONEGRO' 'SAN ALBERTO' 'CHITA' 'SIMITÍ'
 'CHIMICHAGUA' 'NOROSI' 'PUERTO TRIUNFO' 'CURUMANÍ' 'SABANA DE TORRES'
 'PAILITAS' 'CHIMA' 'PUERTO NARE' 'SAN VICENTE DE CHUCURÍ'
 'TIQUISIO (PUERTO RICO)' 'EL BANCO' 'SUCRE' 'MORALES' 'ZAPATOCA' 'ÁBREGO'
 'LA GLORIA' 'TAMALAMEQUE' 'SANTA HELENA DEL OPÓN' 'RIO DE ORO' 'YOLOMBÓ'
 'VÉLEZ' 'EL PEÑÓN' 'LA PAZ' 'CONTRATACIÓN' 'EL GUACAMAYO' 'REGIDOR'
 'HATO' 'YACOPÍ']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  663
(663, 14)
---------------
File:  Cat_sis_SGC_TECTO_2022.xlsx
---------------

['SANTANDER' 'ANTIOQUIA' 'BOLÍVAR' 'BOYACÁ' 'CESAR' 'NORTE DE SANTANDER'
 'MAGDALENA' 'CUNDINAMARCA']

['LANDÁZURI' 'CIMITARRA' 'PUERTO WILCHES' 'YONDÓ (CASABE)' 'EL CARMEN'
 'PUERTO BERRÍO' 'SAN PABLO' 'PUERTO BOYACÁ' 'VÉLEZ' 'SAN ALBERTO'
 'EL PEÑÓN' 'PAILITAS' 'SABANA DE TORRES' 'RIOVIEJO' 'BARRANCABERMEJA'
 'REMEDIOS' 'ÁBREGO' 'SAN VICENTE DE CHUCURÍ' 'SIMACOTA' 'ZAPATOCA'
 'BOLIVAR' 'CANTAGALLO' 'RIONEGRO' 'EL BANCO' 'SANTA HELENA DEL OPÓN'
 'SANTA ROSA DEL SUR' 'GONZÁLEZ' 'ARENAL' 'SAN FRANCISCO' 'YOLOMBÓ'
 'PUERTO TRIUNFO' 'BETULIA' 'SONSÓN' 'TIQUISIO (PUERTO RICO)'
 'PUERTO PARRA' 'BUCARAMANGA' 'FLORIÁN' 'BARRANCO DE LOBA' 'AGUACHICA'
 'LA BELLEZA' 'CHIPATÁ' 'PELAYA' 'SUCRE' 'SIMITÍ' 'CARACOLÍ' 'OCAÑA'
 'SAN MARTÍN' 'GIRÓN' 'LA GLORIA' 'LA ESPERANZA' 'LEBRIJA'
 'HATILLO DE LOBA' 'SAN LUIS' 'MACEO' 'NOROSI' 'SAN ROQUE' 'TINJACÁ'
 'EL PLAYÓN' 'BECERRILL' 'VEGACHÍ' 'SAN MARTIN DE LOBA' 'YACOPÍ'
 'SAN CARLOS' 'OTANCHE' 'ALTOS DEL ROSARIO' 'YALÍ' 'CÁCHIRA' 'PUERTO NARE'
 'HATO' 'CHIMICHAGUA']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  546
(546, 14)
---------------
File:  Cat_sis_SGC_TECTO_2019.xlsx
---------------

['SANTANDER' 'ANTIOQUIA' 'BOLÍVAR' 'CESAR' 'NORTE DE SANTANDER'
 'MAGDALENA' 'BOYACÁ']

['LEBRIJA' 'YONDÓ (CASABE)' 'MORALES' 'PELAYA' 'SIMITÍ' 'SUCRE' 'PAILITAS'
 'AGUSTÍN CODAZZI' 'SAN MARTÍN' 'EL PEÑÓN' 'NOROSI' 'SAN PABLO' 'RIONEGRO'
 'CURUMANÍ' 'CANTAGALLO' 'PUERTO WILCHES' 'LA BELLEZA' 'REMEDIOS'
 'SIMACOTA' 'EL CARMEN' 'SABANA DE TORRES' 'CIMITARRA'
 'SANTA ROSA DEL SUR' 'PUERTO BERRÍO' 'CHIMICHAGUA' 'OCAÑA'
 'SAN FRANCISCO' 'YOLOMBÓ' 'AGUACHICA' 'EL BANCO' 'SAN CARLOS'
 'PUERTO PARRA' 'BUCARAMANGA' 'RIOVIEJO' 'GALÁN' 'SAN VICENTE DE CHUCURÍ'
 'BARRANCABERMEJA' 'ÁBREGO' 'EL PLAYÓN' 'ZAPATOCA' 'TAMALAMEQUE'
 'SANTA HELENA DEL OPÓN' 'BETULIA' 'PUERTO BOYACÁ' 'OTANCHE' 'BECERRILL'
 'SAN ALBERTO' 'VÉLEZ' 'LA JAGUA DE IBIRICO' 'MACEO' 'SAN LUIS' 'BOLIVAR'
 'CÁCHIRA' 'RIO DE ORO' 'CHIRIGUANÁ' 'EL PASO' 'SONSÓN' 'LA GLORIA'
 'LA ESPERANZA' 'PUERTO NARE' 'HATILLO DE LOBA' 'LA PAZ'
 'SAN MARTIN DE LOBA' 'LANDÁZURI' 'VALLEDUPAR' 'BARRANCO DE LOBA' 'GIRÓN'
 'ARENAL' 'CARACOLÍ' 'BOSCONIA' 'ASTREA' 'MATANZA' 'PUERTO TRIUNFO'
 'VEGACHÍ']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  731
(731, 14)
---------------
File:  Cat_sis_SGC_TECTO_2021.xlsx
---------------

['BOLÍVAR' 'ANTIOQUIA' 'SANTANDER' 'NORTE DE SANTANDER' 'BOYACÁ' 'CESAR'
 'MAGDALENA']

['CANTAGALLO' 'YONDÓ (CASABE)' 'PUERTO PARRA' 'RIONEGRO' 'EL CARMEN'
 'SABANA DE TORRES' 'LA PAZ' 'PUERTO BOYACÁ' 'SIMACOTA' 'SAN FRANCISCO'
 'BARRANCABERMEJA' 'PUERTO NARE' 'PUERTO WILCHES' 'SAN VICENTE DE CHUCURÍ'
 'PUERTO BERRÍO' 'CHIRIGUANÁ' 'CIMITARRA' 'SONSÓN' 'SIMITÍ' 'GIRÓN'
 'SUCRE' 'NOROSI' 'OCAÑA' 'SANTA ROSA DEL SUR' 'BOSCONIA' 'PUERTO TRIUNFO'
 'CÁCHIRA' 'VÉLEZ' 'SAN PABLO' 'SAN MARTIN DE LOBA' 'PAILITAS' 'LEBRIJA'
 'GAMARRA' 'BUCARAMANGA' 'LANDÁZURI' 'SAN MARTÍN' 'BOLIVAR' 'CHIMICHAGUA'
 'EL BANCO' 'EL PLAYÓN' 'RIO DE ORO' 'RIOVIEJO' 'SAN LUIS' 'REMEDIOS'
 'LA GLORIA' 'BECERRILL' 'SANTA HELENA DEL OPÓN' 'EL PASO' 'OTANCHE'
 'CURUMANÍ' 'TAMALAMEQUE' 'AGUACHICA' 'FLORIÁN' 'LA BELLEZA' 'BETULIA'
 'YOLOMBÓ' 'TIQUISIO (PUERTO RICO)' 'SAN ALBERTO' 'SAN CARLOS' 'CARACOLÍ'
 'EL PEÑÓN' 'HATILLO DE LOBA' 'ARENAL' 'PELAYA' 'LA ESPERANZA'
 'ALTOS DEL ROSARIO' 'ZAPATOCA' 'MACEO' 'AGUSTÍN CODAZZI'
 'LA JAGUA DE IBIRICO' 'MORALES' 'GALÁN' 'YALÍ' 'HATO']

Index(['FECHA - HORA UTC', 'LATITUD (°)', 'LONGITUD (°)', 'PROF. (Km)',
       'MAGNITUD', 'TIPO MAGNITUD', 'RMS (Seg)', 'GAP (°)',
       'ERROR LATITUD (Km)', 'ERROR LONGITUD (Km)', 'ERROR PROFUNDIDAD (Km)',
       'REGION', 'ESTADO', 'Fecha-Hora UTC', 'Departamento', 'Municipio',
       'FASES'],
      dtype='object')
Eventos:  666
(666, 14)

In [ ]:
df_SGC_TECTO['Catalogo'] = 'TECTO'
df_SGC_TECTO['Profundidad [km]'] = df_SGC_TECTO['Profundidad [km]'].astype(float)
df_SGC_TECTO['Gap'] = df_SGC_TECTO['Gap'].astype(float)
df_SGC_TECTO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          7668 non-null   object
 1   Latitud                 7668 non-null   float64
 2   Longitud                7668 non-null   float64
 3   Profundidad [km]        7668 non-null   float64
 4   Magnitud                7668 non-null   float64
 5   Tipo Magnitud           7668 non-null   object
 6   Error Latitud [km]      7668 non-null   float64
 7   Error Longitud [km]     7668 non-null   float64
 8   Error Profundidad [km]  7668 non-null   float64
 9   Numero de Fases         0 non-null      float64
 10  RMS [seg]               7668 non-null   float64
 11  Gap                     7668 non-null   float64
 12  Departamento            7668 non-null   object
 13  Municipio               7668 non-null   object
 14  Catalogo                7668 non-null   object
dtypes: float64(10), object(5)
memory usage: 898.7+ KB

In [ ]:
df_SGC_TECTO.head()

,Fecha-Hora UTC,Latitud,Longitud,Profundidad [km],Magnitud,Tipo Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],Numero de Fases,RMS [seg],Gap,Departamento,Municipio,Catalogo
0,2017-01-01 02:37:44,8.574,-73.969,19.6,0.8,MLr_vmm,1.5,2.5,3.3,NaN,0.1,188.0,BOLÍVAR,NOROSÍ,TECTO
1,2017-01-01 03:49:24,6.306,-74.647,12.7,1.0,MLr_vmm,4.6,4.1,5.3,NaN,0.3,271.0,ANTIOQUIA,PUERTO NARE,TECTO
2,2017-01-01 09:08:39,7.648,-73.045,0.0,0.7,MLr_vmm,0.8,3.1,3.7,NaN,0.1,218.0,NORTE DE SANTANDER,CÁCHIRA,TECTO
3,2017-01-01 20:54:20,6.204,-73.698,32.0,0.9,MLr_vmm,2.3,1.7,8.3,NaN,0.2,177.0,SANTANDER,LA PAZ,TECTO
4,2017-01-02 10:01:10,7.291,-73.900,33.0,1.3,MLr_vmm,3.9,2.1,6.6,NaN,0.3,162.0,SANTANDER,PUERTO WILCHES,TECTO

## Catalogo LBG

In [ ]:
path_catalogo = os.path.join(path_datasets, 'Cat_sis_SGC_LBG_jun1993_2021')
os.listdir(path_catalogo)

df_SGC_LBG = df_general.copy()

for i in os.listdir(path_catalogo)[:]:
  if i.endswith('.xlsx'):
    print('-----'*3)
    print('File: ', i)
    print('-----'*3)
    df_temp_1 = sup.io.crear_catalogo_SGC_LBG(path_catalogo=path_catalogo,
                                              file_excel=i)

    print(df_temp_1.shape)
    df_SGC_LBG = pd.concat([df_SGC_LBG, df_temp_1], ignore_index=True)
    df_SGC_LBG.reset_index(drop=True, inplace=True)

    del df_temp_1

---------------
File:  Cat_sis_SGC_LBG_1994.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  228
(228, 14)
---------------
File:  Cat_sis_SGC_LBG_1997.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  129
(129, 14)
---------------
File:  Cat_sis_SGC_LBG_2020.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1305
(1305, 14)
---------------
File:  Cat_sis_SGC_LBG_2012.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  773
(773, 14)
---------------
File:  Cat_sis_SGC_LBG_2013.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  609
(609, 14)
---------------
File:  Cat_sis_SGC_LBG_2008.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  199
(199, 14)
---------------
File:  Cat_sis_SGC_LBG_1998.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  276
(276, 14)
---------------
File:  Cat_sis_SGC_LBG_2014.xlsx
---------------

/tmp/ipykernel_7303/2212349628.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_SGC_LBG = pd.concat([df_SGC_LBG, df_temp_1], ignore_index=True)

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1091
(1091, 14)
---------------
File:  Cat_sis_SGC_LBG_1999.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  200
(200, 14)
---------------
File:  Cat_sis_SGC_LBG_2016.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1164
(1164, 14)
---------------
File:  Cat_sis_SGC_LBG_2003.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  311
(311, 14)
---------------
File:  Cat_sis_SGC_LBG_2004.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  225
(225, 14)
---------------
File:  Cat_sis_SGC_LBG_1993.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  120
(120, 14)
---------------
File:  Cat_sis_SGC_LBG_2019.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1491
(1491, 14)
---------------
File:  Cat_sis_SGC_LBG_2011.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  737
(737, 14)
---------------
File:  Cat_sis_SGC_LBG_2010.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  557
(557, 14)
---------------
File:  Cat_sis_SGC_LBG_2017.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1329
(1329, 14)
---------------
File:  Cat_sis_SGC_LBG_2000.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  198
(198, 14)
---------------
File:  Cat_sis_SGC_LBG_2018.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1347
(1347, 14)
---------------
File:  Cat_sis_SGC_LBG_2009.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  440
(440, 14)
---------------
File:  Cat_sis_SGC_LBG_2002.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  314
(314, 14)
---------------
File:  Cat_sis_SGC_LBG_1995.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  245
(245, 14)
---------------
File:  Cat_sis_SGC_LBG_1996.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  158
(158, 14)
---------------
File:  Cat_sis_SGC_LBG_2015.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1075
(1075, 14)
---------------
File:  Cat_sis_SGC_LBG_2001.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  228
(228, 14)
---------------
File:  Cat_sis_SGC_LBG_2021.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  1205
(1205, 14)
---------------
File:  Cat_sis_SGC_LBG_2006.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  175
(175, 14)
---------------
File:  Cat_sis_SGC_LBG_2005.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  214
(214, 14)
---------------
File:  Cat_sis_SGC_LBG_2007.xlsx
---------------

[nan]

[nan]

Index(['Fecha  (UTC)', 'Hora  (UTC)', 'Latitud(°)', 'Longitud(°)',
       'Profundidad(Km)', 'Magnitud', 'Tipo Magnitud', 'Rms(Seg)', 'Gap(°)',
       'Error  Latitud(Km)', 'Error  Longitud(Km)', 'Error  Profundidad(Km)',
       'Modelo', 'Fecha-Hora UTC', 'Departamento', 'Municipio', 'FASES'],
      dtype='object')
Eventos:  138
(138, 14)

In [ ]:
df_SGC_LBG['Catalogo'] = 'LBG'
df_SGC_LBG.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16481 entries, 0 to 16480
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Fecha-Hora UTC          16481 non-null  object
 1   Latitud                 16481 non-null  float64
 2   Longitud                16481 non-null  float64
 3   Profundidad [km]        16481 non-null  float64
 4   Magnitud                16481 non-null  float64
 5   Tipo Magnitud           16481 non-null  object
 6   Error Latitud [km]      16481 non-null  float64
 7   Error Longitud [km]     16481 non-null  float64
 8   Error Profundidad [km]  16481 non-null  float64
 9   Numero de Fases         0 non-null      float64
 10  RMS [seg]               16481 non-null  float64
 11  Gap                     16481 non-null  object
 12  Departamento            0 non-null      object
 13  Municipio               0 non-null      object
 14  Catalogo                16481 non-null  object
dtypes: float64(9), object(6)
memory usage: 1.9+ MB

In [ ]:
df_SGC_LBG.head()

,Fecha-Hora UTC,Latitud,Longitud,Profundidad [km],Magnitud,Tipo Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],Numero de Fases,RMS [seg],Gap,Departamento,Municipio,Catalogo
0,1994-01-01 13:20:05,4.936,-74.605,11.6,1.8,ML,2.2,2.0,15.1,NaN,0.4,128,NaN,NaN,LBG
1,1994-01-01 03:52:24,4.828,-74.563,17.3,1.8,ML,9.0,10.8,11.0,NaN,0.7,127,NaN,NaN,LBG
2,1994-01-01 15:24:32,4.739,-74.682,8.1,1.8,ML,10.6,10.3,25.9,NaN,0.5,102,NaN,NaN,LBG
3,1994-01-01 20:10:36,5.702,-74.598,3.4,2.5,ML,3.6,3.6,9.3,NaN,1.0,116,NaN,NaN,LBG
4,1994-01-03 07:37:51,5.231,-74.730,14.0,1.7,ML,2.3,2.6,6.8,NaN,0.4,144,NaN,NaN,LBG

# Unir catalogos

In [ ]:
df_unido = pd.concat([df_SGC_1, df_SGC_2, df_SGC_TECTO, df_SGC_LBG], ignore_index=True)
df_unido.reset_index(drop=True, inplace=True)

df_unido['Tiempo'] = pd.to_datetime(df_unido['Fecha-Hora UTC'])

df_unido.head()

,Fecha-Hora UTC,Latitud,Longitud,Profundidad [km],Magnitud,Tipo Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],Numero de Fases,RMS [seg],Gap,Departamento,Municipio,Catalogo,Tiempo
0,2010-01-01 01:55:52,6.504,-74.471,4.0,1.6,Ml,10.0,4.2,11.9,5,0.6,220.0,ANTIOQUIA,PUERTO BERRIO,SGC 1,2010-01-01 01:55:52
1,2010-01-01 04:19:45,6.775,-72.869,143.4,1.4,Ml,6.4,11.8,7.9,5,0.4,240.0,SANTANDER,SAN ANDRES,SGC 1,2010-01-01 04:19:45
2,2010-01-01 07:33:57,6.773,-73.080,148.0,1.6,Ml,2.4,6.9,4.8,6,0.3,189.0,SANTANDER,LOS SANTOS,SGC 1,2010-01-01 07:33:57
3,2010-01-01 07:40:27,6.776,-73.032,156.0,1.1,Ml,5.3,45.2,15.2,5,0.3,194.0,SANTANDER,CEPITA,SGC 1,2010-01-01 07:40:27
4,2010-01-01 08:46:08,6.823,-73.023,137.6,1.9,Ml,5.4,10.2,11.4,9,0.5,135.0,SANTANDER,CEPITA,SGC 1,2010-01-01 08:46:08

In [ ]:
df_unido['Catalogo'].unique()

array(['SGC 1', 'SGC 2', 'TECTO', 'LBG'], dtype=object)

In [ ]:
df_unido.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303240 entries, 0 to 303239
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fecha-Hora UTC          303240 non-null  object
 1   Latitud                 303240 non-null  float64
 2   Longitud                303240 non-null  float64
 3   Profundidad [km]        303240 non-null  float64
 4   Magnitud                303240 non-null  float64
 5   Tipo Magnitud           303240 non-null  object
 6   Error Latitud [km]      303106 non-null  float64
 7   Error Longitud [km]     303106 non-null  float64
 8   Error Profundidad [km]  303106 non-null  float64
 9   Numero de Fases         279091 non-null  object
 10  RMS [seg]               303106 non-null  float64
 11  Gap                     303106 non-null  object
 12  Departamento            286759 non-null  object
 13  Municipio               285004 non-null  object
 14  Catalogo                303240 non-null  object
 15  Tiempo                  303240 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(8), object(7)
memory usage: 37.0+ MB

In [ ]:
df_unido.describe().round(2)

,Latitud,Longitud,Profundidad [km],Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],RMS [seg],Tiempo
count,303240.00,303240.00,303240.00,303240.00,303106.00,303106.00,303106.00,303106.00,303240
mean,6.58,-73.51,101.06,1.90,4.46,5.95,7.69,0.49,2015-07-06 19:47:00.099531520
min,3.00,-76.00,-4.97,0.00,0.00,0.00,0.00,0.00,1993-06-01 01:32:55
25%,6.42,-73.77,30.13,1.50,2.00,2.10,3.40,0.30,2011-08-20 23:17:01.750000128
50%,6.79,-73.18,136.10,1.80,3.40,4.07,6.00,0.40,2017-08-08 04:09:50.500000
75%,6.84,-73.12,145.60,2.20,5.30,7.00,8.70,0.60,2021-04-17 14:51:00.750000128
max,11.00,-71.01,594.80,6.80,999.00,999.00,999.00,10.00,2024-12-31 23:39:56
std,1.23,0.73,58.40,0.66,8.58,8.83,19.56,0.28,NaN

## Duplicados

In [ ]:
df_unido.duplicated(subset=['Fecha-Hora UTC', 'Latitud', 'Longitud'], keep='first').sum()
#  duplicados

np.int64(22154)

In [ ]:
df_unido['Tipo Magnitud'].unique()

array(['Ml', 'Mw', 'MLr_vmm', 'MLr_3', 'MLr_2', 'MLr_1', 'MLr_4',
       'Mw(mB)', 'M_MLr', 'MLr_PtoGtn', 'MLr', 'M', 'MLr_5', 'mb', 'MLv',
       'mB', 'M_Pac', 'Mwp', 'ML'], dtype=object)

In [ ]:
df_unido['Tipo Magnitud 2'] = df_unido['Tipo Magnitud'].str.lower()
df_unido['Tipo Magnitud 2'].unique()

array(['ml', 'mw', 'mlr_vmm', 'mlr_3', 'mlr_2', 'mlr_1', 'mlr_4',
       'mw(mb)', 'm_mlr', 'mlr_ptogtn', 'mlr', 'm', 'mlr_5', 'mb', 'mlv',
       'm_pac', 'mwp'], dtype=object)

In [ ]:
df_unido.describe()

,Latitud,Longitud,Profundidad [km],Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],RMS [seg],Tiempo
count,303240.000000,303240.000000,303240.000000,303240.000000,303106.000000,303106.000000,303106.000000,303106.000000,303240
mean,6.580466,-73.511873,101.059301,1.904443,4.462535,5.949131,7.689872,0.492964,2015-07-06 19:47:00.099531520
min,3.000000,-76.000000,-4.970000,0.000000,0.000000,0.000000,0.000000,0.000000,1993-06-01 01:32:55
25%,6.416000,-73.768000,30.127500,1.500000,2.000000,2.100000,3.400000,0.300000,2011-08-20 23:17:01.750000128
50%,6.787000,-73.181500,136.100000,1.800000,3.400000,4.069000,6.000000,0.400000,2017-08-08 04:09:50.500000
75%,6.836000,-73.122000,145.600000,2.200000,5.303000,7.002750,8.700000,0.600000,2021-04-17 14:51:00.750000128
max,11.000000,-71.011000,594.800000,6.800000,999.000000,999.000000,999.000000,10.000000,2024-12-31 23:39:56
std,1.231248,0.728092,58.400599,0.664271,8.581627,8.831882,19.562266,0.275579,NaN

In [ ]:
df_unido.sort_values(by=['Tiempo', 'Tipo Magnitud 2'],
                     ascending=True,
                     inplace=True)

Se considerarán únicamente los eventos que cuenten con ML como tipo de magnitud.

In [ ]:
filtro_ml = df_unido['Tipo Magnitud 2'].str.contains('ml')

df_unido[filtro_ml]['Tipo Magnitud 2'].unique()

array(['ml', 'mlr', 'mlr_vmm', 'mlr_4', 'mlr_2', 'mlr_3', 'm_mlr',
       'mlr_1', 'mlr_ptogtn', 'mlr_5', 'mlv'], dtype=object)

In [ ]:
df_unido.duplicated(subset=['Fecha-Hora UTC', 'Latitud', 'Longitud'], keep='first').sum()
# 22154 duplicados

np.int64(22154)

In [ ]:
df_filtrado = df_unido.copy()
df_filtrado.drop_duplicates(subset=['Fecha-Hora UTC', 'Latitud', 'Longitud'], keep='first', inplace=True)
df_filtrado.reset_index(drop=True, inplace=True)

In [ ]:
df_filtrado.duplicated(subset=['Fecha-Hora UTC', 'Latitud', 'Longitud'], keep='first').sum()
# Ya no se tienen duplicados

np.int64(0)

In [ ]:
df_filtrado.describe().round(2)

,Latitud,Longitud,Profundidad [km],Magnitud,Error Latitud [km],Error Longitud [km],Error Profundidad [km],RMS [seg],Tiempo
count,281086.00,281086.00,281086.00,281086.00,280952.00,280952.00,280952.00,280952.00,281086
mean,6.58,-73.47,106.61,1.91,4.46,6.05,7.35,0.50,2015-08-06 12:41:22.378137344
min,3.00,-76.00,-4.97,0.00,0.00,0.00,0.00,0.00,1993-06-01 01:32:55
25%,6.54,-73.70,62.00,1.50,2.09,2.18,3.40,0.30,2011-07-24 20:23:13.249999872
50%,6.79,-73.18,138.00,1.80,3.50,4.20,6.10,0.40,2017-10-14 19:12:13.500000
75%,6.83,-73.12,146.00,2.20,5.40,7.21,8.70,0.60,2021-06-27 06:10:59.750000128
max,11.00,-71.01,594.80,6.80,313.47,283.69,832.90,10.00,2024-12-31 23:39:56
std,1.21,0.72,55.74,0.64,4.88,7.01,8.22,0.28,NaN

In [ ]:
df_filtrado[df_filtrado['Profundidad [km]'] <= 60].to_csv('df_lq60km.csv',
                                                          decimal=',',
                                                          sep=';',
                                                          index=False)

## Geodataframe

In [ ]:
gdf_filtrado = gpd.GeoDataFrame(
    df_filtrado, geometry=gpd.points_from_xy(df_filtrado.Longitud, df_filtrado.Latitud), crs="EPSG:4326"
)

In [ ]:
gdf_filtrado = gdf_filtrado.to_crs(9377)

In [ ]:
df_filtrado['X [m]'] = gdf_filtrado.get_coordinates()['x']
df_filtrado['Y [m]'] = gdf_filtrado.get_coordinates()['y']

df_filtrado['X [km]'] = df_filtrado['X [m]'] / 1000
df_filtrado['Y [km]'] = df_filtrado['Y [m]'] / 1000

df_filtrado.head()

## Punto referencia Campo Colorado

In [ ]:
punto_xy_CampoColorado = (4919222.973, 2308553.476) # x, y en metros

# se va calcular la distancia de los eventos al centroide o punto de referencia
# del Campo Colorado solo en XY mas no en profundidad

df_filtrado['Distancia [m]'] = np.sqrt((df_filtrado['X [m]'] - punto_xy_CampoColorado[0])**2 + (df_filtrado['Y [m]'] - punto_xy_CampoColorado[1])**2)
df_filtrado['Distancia [km]'] = df_filtrado['Distancia [m]'] / 1000

df_filtrado.describe().round(2)

## Subcatalogos

In [ ]:
limites_BSN = {'longitud': [-73.40, -72.80],
               'latitud': [6.50, 7.10]}
limites_CC = {'longitud': [-74.19, -73.26],
              'latitud': [6.32, 7.25]}

In [ ]:
df_FC = df_filtrado.copy()

filtro_BSN = (df_filtrado['Longitud'] >= limites_BSN['longitud'][0]) & (df_filtrado['Longitud'] <= limites_BSN['longitud'][1]) & (df_filtrado['Latitud'] >= limites_BSN['latitud'][0]) & (df_filtrado['Latitud'] <= limites_BSN['latitud'][1])
df_BSN = df_filtrado[filtro_BSN].copy()

filtro_CC = (df_filtrado['Longitud'] >= limites_CC['longitud'][0]) & (df_filtrado['Longitud'] <= limites_CC['longitud'][1]) & (df_filtrado['Latitud'] >= limites_CC['latitud'][0]) & (df_filtrado['Latitud'] <= limites_CC['latitud'][1])
df_CC = df_filtrado[filtro_CC].copy()

In [ ]:
df_FC.describe().round(2)

In [ ]:
df_BSN.describe().round(2)

In [ ]:
df_CC.describe().round(2)

In [ ]:
total_eventos_FC = df_FC.shape[0]
total_eventos_BSN = df_BSN.shape[0]
total_eventos_CC = df_CC.shape[0]

porcentaje_eventos_FC = (total_eventos_FC / total_eventos_FC) * 100
porcentaje_eventos_BSN = (total_eventos_BSN / total_eventos_FC) * 100
porcentaje_eventos_CC = (total_eventos_CC / total_eventos_FC) * 100

print(f'Total de eventos FC: {total_eventos_FC} [{porcentaje_eventos_FC:.2f}%]')
print(f'Total de eventos BSN: {total_eventos_BSN} [{porcentaje_eventos_BSN:.2f}%]')
print(f'Total de eventos CC: {total_eventos_CC} [{porcentaje_eventos_CC:.2f}%]')

Después de aplicar el filtrado del catálogo (considerando únicamente eventos con ML como tipo de magnitud), se obtiene:

* `FC` (Full Catalog): 281086 eventos (100% del conjunto de estudio).
* `BSN` (Bucaramanga Seismic Nest Catalog): 161158 eventos, equivalentes al 57.33% del `FC`.
* `CC` (Campo Colorado Catalog): 22052 eventos, equivalentes al 7.85% del `FC`.

# Histogramas errores

In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=3, figsize=(12,8))

# FC
sup.plots.histograma_plot(df= df_FC,
                          columna= 'X [km]',
                          ax_h= ax[0,0],
                          dist_min= df_FC['X [km]'].min(),
                          units_label='km',
                          step_= 20)
sup.plots.histograma_plot(df= df_FC,
                          columna= 'Error Longitud [km]',
                          ax_h= ax[1,0],
                          dist_min= 0,
                          units_label='km',
                          step_= 10)
ax[0,0].set_xlabel('X [km] - FC')
ax[1,0].set_xlabel('X Error [km] - FC')

# BSN
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'X [km]',
                          ax_h= ax[0,1],
                          dist_min= df_BSN['X [km]'].min(),
                          units_label='km',
                          step_= 5)
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'Error Longitud [km]',
                          ax_h= ax[1,1],
                          dist_min= 0,
                          units_label='km',
                          step_= 5)
ax[0,1].set_xlabel('X [km] - BSN')
ax[1,1].set_xlabel('X Error [km] - BSN')

# CC
sup.plots.histograma_plot(df= df_CC,
                          columna= 'X [km]',
                          ax_h= ax[0,2],
                          dist_min= df_CC['X [km]'].min(),
                          units_label='km',
                          step_= 5)
sup.plots.histograma_plot(df= df_CC,
                          columna= 'Error Longitud [km]',
                          ax_h= ax[1,2],
                          dist_min= 0,
                          units_label='km',
                          step_= 5)
ax[0,2].set_xlabel('X [km] - CC')
ax[1,2].set_xlabel('X Error [km] - CC')

ax[0,0].set_title('FC Catalog')
ax[0,1].set_title('BSN Catalog')
ax[0,2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'hits_errores_coorX',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=3, figsize=(12,8))

# FC
sup.plots.histograma_plot(df= df_FC,
                          columna= 'Y [km]',
                          ax_h= ax[0,0],
                          dist_min= df_FC['Y [km]'].min(),
                          step_= 20)
sup.plots.histograma_plot(df= df_FC,
                          columna= 'Error Latitud [km]',
                          ax_h= ax[1,0],
                          dist_min= 0,
                          step_= 10)
ax[0,0].set_xlabel('Y [km] - FC')
ax[1,0].set_xlabel('Y Error [km] - FC')

# BSN
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'Y [km]',
                          ax_h= ax[0,1],
                          dist_min= df_BSN['Y [km]'].min(),
                          step_= 5)
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'Error Latitud [km]',
                          ax_h= ax[1,1],
                          dist_min= 0,
                          step_= 5)
ax[0,1].set_xlabel('Y [km] - BSN')
ax[1,1].set_xlabel('Y Error [km] - BSN')

# CC
sup.plots.histograma_plot(df= df_CC,
                          columna= 'Y [km]',
                          ax_h= ax[0,2],
                          dist_min= df_CC['Y [km]'].min(),
                          step_= 5)
sup.plots.histograma_plot(df= df_CC,
                          columna= 'Error Latitud [km]',
                          ax_h= ax[1,2],
                          dist_min= 0,
                          step_= 5)
ax[0,2].set_xlabel('Y [km] - CC')
ax[1,2].set_xlabel('Y Error [km] - CC')

ax[0,0].set_title('FC Catalog')
ax[0,1].set_title('BSN Catalog')
ax[0,2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'hits_errores_coorY',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=3, figsize=(12,8))

# FC
sup.plots.histograma_plot(df= df_FC,
                          columna= 'Profundidad [km]',
                          ax_h= ax[0,0],
                          dist_min= df_FC['Profundidad [km]'].min(),
                          step_= 20)
sup.plots.histograma_plot(df= df_FC,
                          columna= 'Error Profundidad [km]',
                          ax_h= ax[1,0],
                          dist_min= 0,
                          step_= 20)
ax[0,0].set_xlabel('Depth [km] - FC')
ax[1,0].set_xlabel('Depth Error [km] - FC')

# BSN
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'Profundidad [km]',
                          ax_h= ax[0,1],
                          dist_min= df_BSN['Profundidad [km]'].min(),
                          step_= 20)
sup.plots.histograma_plot(df= df_BSN,
                          columna= 'Error Profundidad [km]',
                          ax_h= ax[1,1],
                          dist_min= 0,
                          step_= 5)
ax[0,1].set_xlabel('Depth [km] - BSN')
ax[1,1].set_xlabel('Depth Error [km] - BSN')

# CC
sup.plots.histograma_plot(df= df_CC,
                          columna= 'Profundidad [km]',
                          ax_h= ax[0,2],
                          dist_min= df_CC['Profundidad [km]'].min(),
                          step_= 10)
sup.plots.histograma_plot(df= df_CC,
                          columna= 'Error Profundidad [km]',
                          ax_h= ax[1,2],
                          dist_min= 0,
                          step_= 5)
ax[0,2].set_xlabel('Depth [km] - CC')
ax[1,2].set_xlabel('Depth Error [km] - CC')

ax[0,0].set_title('FC Catalog')
ax[0,1].set_title('BSN Catalog')
ax[0,2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'hits_errores_profundidad',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

# Tiempo vs magnitud

## Profundidad limite

In [ ]:
profundidad_corte = 60

In [ ]:
fig, ax = plt.subplots(ncols=1, nrows=3, figsize=(8,11))

# FC
filtro_datos = df_FC['Profundidad [km]'] <= profundidad_corte
sup.plots.time_magnitud_plot(df = df_FC,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[0],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $\leq{profundidad_corte}$ km]')
ax[0].legend()
ax[0].set_xlabel('Time')
ax[0].set_ylabel('Magnitude')
ax[0].set_title('FC Catalog')


# BSN
filtro_datos = df_BSN['Profundidad [km]'] <= profundidad_corte
sup.plots.time_magnitud_plot(df = df_BSN,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[1],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $\leq{profundidad_corte}$ km]')
ax[1].legend()
ax[1].set_xlabel('Time')
ax[1].set_ylabel('Magnitude')
ax[1].set_title('BSN Catalog')

# CC
filtro_datos = df_CC['Profundidad [km]'] <= profundidad_corte
sup.plots.time_magnitud_plot(df = df_CC,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[2],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $\leq{profundidad_corte}$ km]')
ax[2].legend()
ax[2].set_xlabel('Time')
ax[2].set_ylabel('Magnitude')
ax[2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'scatter_tiempo_magnitud_somero',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

In [ ]:
fig, ax = plt.subplots(ncols=1, nrows=3, figsize=(8,11))

# FC
filtro_datos = df_FC['Profundidad [km]'] > profundidad_corte
sup.plots.time_magnitud_plot(df = df_FC,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[0],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $>{profundidad_corte}$ km]')
ax[0].legend()
ax[0].set_xlabel('Time')
ax[0].set_ylabel('Magnitude')
ax[0].set_title('FC Catalog')


# BSN
filtro_datos = df_BSN['Profundidad [km]'] > profundidad_corte
sup.plots.time_magnitud_plot(df = df_BSN,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[1],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $>{profundidad_corte}$ km]')
ax[1].legend()
ax[1].set_xlabel('Time')
ax[1].set_ylabel('Magnitude')
ax[1].set_title('BSN Catalog')

# CC
filtro_datos = df_CC['Profundidad [km]'] > profundidad_corte
sup.plots.time_magnitud_plot(df = df_CC,
                             filtro_datos = filtro_datos,
                             columna_eje_x_tiempo = 'Tiempo',
                             comlumna_eje_y = 'Magnitud',
                             ax_s = ax[2],
                             label_s= f'{filtro_datos.sum()} Earthquakes [Depth $>{profundidad_corte}$ km]')
ax[2].legend()
ax[2].set_xlabel('Time')
ax[2].set_ylabel('Magnitude')
ax[2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'scatter_tiempo_magnitud_profundos',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

# Histograma magnitudes

In [ ]:
steps_magnitud = 0.2
mag_min = 0
mag_max = 8

fig, ax = plt.subplots(nrows=2, ncols=3, figsize=(12,8))

# FC
# <= profunidad corte
filtro_datos = df_FC['Profundidad [km]'] <= profundidad_corte
df_FC_temp = df_FC[filtro_datos]
sup.plots.histograma_plot(df= df_FC_temp,
                          columna= 'Magnitud',
                          ax_h= ax[0,0],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[0,0].set_xlabel(f'Magnitude [Depth $\leq{profundidad_corte}$ km] - FC')
# > profunidad corte
filtro_datos = df_FC['Profundidad [km]'] > profundidad_corte
df_FC_temp = df_FC[filtro_datos]
sup.plots.histograma_plot(df= df_FC_temp,
                          columna= 'Magnitud',
                          ax_h= ax[1,0],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[1,0].set_xlabel(f'Magnitude [Depth $>{profundidad_corte}$ km] - FC')

# BSN
# <= profunidad corte
filtro_datos = df_BSN['Profundidad [km]'] <= profundidad_corte
df_BSN_temp = df_BSN[filtro_datos]
sup.plots.histograma_plot(df= df_BSN_temp,
                          columna= 'Magnitud',
                          ax_h= ax[0,1],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[0,1].set_xlabel(f'Magnitude [Depth $\leq{profundidad_corte}$ km] - BSN')
# > profunidad corte
filtro_datos = df_BSN['Profundidad [km]'] > profundidad_corte
df_BSN_temp = df_BSN[filtro_datos]
sup.plots.histograma_plot(df= df_BSN_temp,
                          columna= 'Magnitud',
                          ax_h= ax[1,1],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[1,1].set_xlabel(f'Magnitude [Depth $>{profundidad_corte}$ km] - BSN')

# CC
# <= profunidad corte
filtro_datos = df_CC['Profundidad [km]'] <= profundidad_corte
df_CC_temp = df_CC[filtro_datos]
sup.plots.histograma_plot(df= df_CC_temp,
                          columna= 'Magnitud',
                          ax_h= ax[0,2],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[0,2].set_xlabel(f'Magnitude [Depth $\leq{profundidad_corte}$ km] - CC')
# > profunidad corte
filtro_datos = df_CC['Profundidad [km]'] > profundidad_corte
df_CC_temp = df_CC[filtro_datos]
sup.plots.histograma_plot(df= df_CC_temp,
                          columna= 'Magnitud',
                          ax_h= ax[1,2],
                          dist_min= mag_min,
                          dist_max= mag_max,
                          units_label='Ml',
                          step_= steps_magnitud)
ax[1,2].set_xlabel(f'Magnitude [Depth $>{profundidad_corte}$ km] - CC')

ax[0,0].set_title('FC Catalog')
ax[0,1].set_title('BSN Catalog')
ax[0,2].set_title('CC Catalog')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'hits_magnitudes_',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

## Cantidad eventos al año

In [ ]:
year_range = np.arange(df_FC['Tiempo'].dt.year.min(),
                       df_FC['Tiempo'].dt.year.max()+1)

fig, ax = plt.subplots(ncols=1, nrows=3, figsize=(7,9), sharex=True)

# Todos
sns.histplot(x = df_FC['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[0],
             legend= True,
             label= f'FC Catalog',
             element='step',
             fill=False)
sns.histplot(x = df_BSN['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[0],
             legend= True,
             label= f'BSN Catalog',
             element='step',
             fill=False)
sns.histplot(x = df_CC['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[0],
             legend= True,
             label= f'CC Catalog',
             element='step',
             fill=False)
ax[0].set_yscale('log')
ax[0].grid(ls='--', c='gray', alpha=0.7)
ax[0].legend()
ax[0].set_ylabel('Number of earthquakes')

# Someros
filtro_datos = df_FC['Profundidad [km]'] <= profundidad_corte
df_FC_temp = df_FC[filtro_datos].copy()
sns.histplot(x = df_FC_temp['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[1],
             legend= True,
             label= f'FC Catalog',
             element='step',
             fill=False)

filtro_datos = df_BSN['Profundidad [km]'] <= profundidad_corte
df_BSN_temp = df_BSN[filtro_datos].copy()
sns.histplot(x = df_BSN_temp['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[1],
             legend= True,
             label= f'BSN Catalog',
             element='step',
             fill=False)


filtro_datos = df_CC['Profundidad [km]'] > profundidad_corte
df_CC_temp = df_CC_temp[filtro_datos].copy()
sns.histplot(x = df_CC['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[1],
             legend= True,
             label= f'CC Catalog',
             element='step',
             fill=False)
ax[1].set_yscale('log')
ax[1].grid(ls='--', c='gray', alpha=0.7)
ax[1].legend()
ax[1].set_ylabel('Number of earthquakes')

# Profundos
filtro_datos = df_FC['Profundidad [km]'] > profundidad_corte
df_FC_temp = df_FC[filtro_datos].copy()
sns.histplot(x = df_FC_temp['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[2],
             legend= True,
             label= f'FC Catalog',
             element='step',
             fill=False)

filtro_datos = df_BSN['Profundidad [km]'] > profundidad_corte
df_BSN_temp = df_BSN[filtro_datos].copy()
sns.histplot(x = df_BSN_temp['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[2],
             legend= True,
             label= f'BSN Catalog',
             element='step',
             fill=False)


filtro_datos = df_CC['Profundidad [km]'] <= profundidad_corte
df_CC_temp = df_CC_temp[filtro_datos].copy()
sns.histplot(x = df_CC['Tiempo'].dt.year,
             #log_scale = (False, True),
             bins = year_range,
             ax= ax[2],
             legend= True,
             label= f'CC Catalog',
             element='step',
             fill=False)
ax[2].set_yscale('log')
ax[2].grid(ls='--', c='gray', alpha=0.7)
ax[2].legend()
ax[2].set_ylabel('Number of earthquakes')
ax[2].set_xlabel('Time')

#ax[2].set_xlabel('')
ax[2].legend()
ax[2].grid(ls='--', c='gray', alpha=0.7)


ax[0].set_title(f'All depths')
ax[1].set_title(f'Depth $\leq{profundidad_corte}$ km')
ax[2].set_title(f'Depth $>{profundidad_corte}$ km')

ax[2].set_xticks(np.arange(start=1990, stop=2025, step=2))
ax[2].set_xlim(left=1993, right=2024)

plt.suptitle(f'Number of earthquakes per year')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = f'cantidad_eventos_anuales',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

En la gráfica de número de eventos por año, el BSN muestra menos de 100 eventos anuales para profundidades someras, lo que dificulta la estimación confiable de los parámetros de Gutenberg–Richter a escala anual. Por esta razón, los cálculos se realizarán de manera acumulativa en etapas posteriores del análisis, y no de forma anual.

# Calculos N

In [ ]:
mag_min = 0
mag_max = 10
steps_mag = 0.1

## Todo el catalogo

In [ ]:
diccionario_FC = {}
diccionario_BSN = {}
diccionario_CC = {}

In [ ]:
diccionario_FC['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_FC['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_FC['get_N']

In [ ]:
diccionario_BSN['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_BSN['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_BSN['get_N']

In [ ]:
diccionario_CC['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_CC['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_CC['get_N']

## Eventos someros

In [ ]:
diccionario_FC_somero = {}
diccionario_BSN_somero = {}
diccionario_CC_somero = {}

filtro_datos = df_FC['Profundidad [km]'] <= profundidad_corte
df_FC_temp = df_FC[filtro_datos]

filtro_datos = df_BSN['Profundidad [km]'] <= profundidad_corte
df_BSN_temp = df_BSN[filtro_datos]

filtro_datos = df_CC['Profundidad [km]'] <= profundidad_corte
df_CC_temp = df_CC[filtro_datos]

In [ ]:
diccionario_FC_somero['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_FC_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_FC_somero['get_N']

In [ ]:
diccionario_BSN_somero['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_BSN_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_BSN_somero['get_N']

In [ ]:
diccionario_CC_somero['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_CC_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_CC_somero['get_N']

## Eventos profundos

In [ ]:
diccionario_FC_profundo = {}
diccionario_BSN_profundo = {}
diccionario_CC_profundo = {}

filtro_datos = df_FC['Profundidad [km]'] > profundidad_corte
df_FC_temp = df_FC[filtro_datos]

filtro_datos = df_BSN['Profundidad [km]'] > profundidad_corte
df_BSN_temp = df_BSN[filtro_datos]

filtro_datos = df_CC['Profundidad [km]'] > profundidad_corte
df_CC_temp = df_CC[filtro_datos]

In [ ]:
diccionario_FC_profundo['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_FC_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_FC_profundo['get_N']

In [ ]:
diccionario_BSN_profundo['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_BSN_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_BSN_profundo['get_N']

In [ ]:
diccionario_CC_profundo['get_N'] = sup.stats.obtener_N_LGR(magnitudes_array = df_CC_temp['Magnitud'].values,
                                                  magnitud_minima = mag_min,
                                                  magnitud_maxima = mag_max,
                                                  steps_ = steps_mag,
                                                  texto = False)

diccionario_CC_profundo['get_N']

### Grafico N

In [ ]:
fig, ax = plt.subplots(nrows=3, ncols=3, figsize=(10,10),
                       sharey='row', sharex='all')

titles_ = ['FC', 'BSN', 'CC']
# Todos
for index_, diccionario in enumerate([diccionario_FC,
                                      diccionario_BSN,
                                      diccionario_CC]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes= diccionario['get_N']['m'],
                                          ax_h= ax[0, index_],
                                          magnitud_maxima= mag_max)
  if index_ > 0:
    ax[0, index_].set_ylabel('')
  ax[0, index_].set_xlabel('')
  ax[0, index_].set_title(f'{titles_[index_]} - All depths')

# Someros
for index_, diccionario in enumerate([diccionario_FC_somero,
                                      diccionario_BSN_somero,
                                      diccionario_CC_somero]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes= diccionario['get_N']['m'],
                                          ax_h= ax[1, index_],
                                          magnitud_maxima= mag_max)
  if index_ > 0:
    ax[1, index_].set_ylabel('')
  ax[1, index_].set_xlabel('')
  ax[1, index_].set_title(f'{titles_[index_]} - Depth $\leq{profundidad_corte}$ km')

# Profundos
for index_, diccionario in enumerate([diccionario_FC_profundo,
                                      diccionario_BSN_profundo,
                                      diccionario_CC_profundo]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes= diccionario['get_N']['m'],
                                          ax_h= ax[2, index_],
                                          magnitud_maxima= mag_max)
  if index_ > 0:
    ax[2, index_].set_ylabel('')
  ax[2, index_].set_xlabel('')
  ax[2, index_].set_title(f'{titles_[index_]} - Depth $>{profundidad_corte}$ km')

ax[2, 0].set_xlabel('Magnitude')
ax[2, 1].set_xlabel('Magnitude')
ax[2, 2].set_xlabel('Magnitude')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'grafico_N_m_',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

# Calculo Gutenberg Richter

Para el cálculo de los parámetros a-value y b-value se empleará la metodología Boosted 2 (donde Mc se determina mediante el criterio de máxima curvatura), dado que en las pruebas preliminares fue la que produjo resultados más cercanos a los reportados por Londoño et al. (2019). A diferencia de dicho estudio, donde se aplican filtros que eliminan una fracción importante del catálogo, en este trabajo no se han descartado eventos, salvo el criterio de disponibilidad de ML como tipo de magnitud. Esta decisión busca conservar la muestra estadística lo más completa posible en cada subcatálogo.

Además, considerando que una parte del proyecto está orientada a la prevención sísmica, se optó por incluir la mayor cantidad de eventos registrados en la zona. Aunque la calidad de algunos eventos puede estar condicionada por diversos factores (por ejemplo, la densidad y cobertura de la red de estaciones), su inclusión aporta información sobre la ocurrencia sísmica y permite evaluar el comportamiento del catálogo bajo un enfoque más conservador.

Bajo estas consideraciones, se implementará el método Boosted utilizando un esquema de remuestreo del 80% de los datos sin reemplazo.

In [ ]:
mag_min = 0
mag_max = 10
steps_mag = 0.1
porcentaje_remuestreo = 0.8
numero_remuestreos = 1000
reemplazo = False
correcion_mc = 0.0

## Todo el catalogo

In [ ]:
diccionario_FC['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_FC['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_FC['Boosted']

In [ ]:
diccionario_BSN['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_BSN['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_BSN['Boosted']

In [ ]:
diccionario_CC['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_CC['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_CC['Boosted']

## Eventos someros

In [ ]:
filtro_datos = df_FC['Profundidad [km]'] <= profundidad_corte
df_FC_temp = df_FC[filtro_datos].copy()

filtro_datos = df_BSN['Profundidad [km]'] <= profundidad_corte
df_BSN_temp = df_BSN[filtro_datos].copy()

filtro_datos = df_CC['Profundidad [km]'] <= profundidad_corte
df_CC_temp = df_CC[filtro_datos].copy()

In [ ]:
diccionario_FC_somero['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_FC_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_FC_somero['Boosted']

In [ ]:
diccionario_BSN_somero['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_BSN_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_BSN_somero['Boosted']

In [ ]:
diccionario_CC_somero['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_CC_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_CC_somero['Boosted']

## Eventos profundos

In [ ]:
filtro_datos = df_FC['Profundidad [km]'] > profundidad_corte
df_FC_temp = df_FC[filtro_datos].copy()

filtro_datos = df_BSN['Profundidad [km]'] > profundidad_corte
df_BSN_temp = df_BSN[filtro_datos].copy()

filtro_datos = df_CC['Profundidad [km]'] > profundidad_corte
df_CC_temp = df_CC[filtro_datos].copy()

In [ ]:
diccionario_FC_profundo['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_FC_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_FC_profundo['Boosted']

In [ ]:
diccionario_BSN_profundo['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_BSN_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_BSN_somero['Boosted']

In [ ]:
diccionario_CC_profundo['Boosted'] = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = df_CC_temp['Magnitud'],
                                                           percentage_data = porcentaje_remuestreo, # 0.8
                                                           magnitud_minima = mag_min,
                                                           magnitud_maxima = mag_max,
                                                           steps_ = steps_mag,
                                                           n_resamples = numero_remuestreos,
                                                           replace_ = reemplazo,
                                                           correcion_m = correcion_mc)

diccionario_CC_profundo['Boosted']

## Dataframe GR

In [ ]:
estadisticos = ['mc_mean', 'mc_std',
                'b_mean', 'b_std',
                'a_mean', 'a_std']

lista_diccionarios = {'FC': diccionario_FC,
                      'BSN': diccionario_BSN,
                      'CC': diccionario_CC,
                      'FC somero': diccionario_FC_somero,
                      'BSN somero': diccionario_BSN_somero,
                      'CC somero': diccionario_CC_somero,
                      'FC profundo': diccionario_FC_profundo,
                      'BSN profundo': diccionario_BSN_profundo,
                      'CC profundo': diccionario_CC_profundo,}

diccionario_vacio = {}

for key, diccionario in lista_diccionarios.items():
  diccionario_vacio[key] = []
  for estadistico in estadisticos:
    diccionario_vacio[key].append(diccionario['Boosted'][estadistico])

df_GR_todos = pd.DataFrame(diccionario_vacio)
df_GR_todos.index = estadisticos

df_GR_todos.round(2)

In [ ]:
df_GR_todos.to_csv(path_or_buf = os.path.join(path_save_figures, 'df_GR_todos.csv'),
                   sep=';',
                   decimal=',',
                   index=True)

### Grafico GR

In [ ]:
min_max_GR = [1.0, 7.0]

fig, ax = plt.subplots(nrows=3, ncols=3, figsize=(10,10),
                       sharey='row', sharex='all')

titles_ = ['FC', 'BSN', 'CC']
# Todos
for index_, diccionario in enumerate([diccionario_FC,
                                      diccionario_BSN,
                                      diccionario_CC]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes = diccionario['get_N']['m'],
                                          ax_h = ax[0, index_],
                                          mc = diccionario['Boosted']['mc_mean'].round(2),
                                          magnitud_maxima= mag_max)
  sup.plots.GutenbergRichter_line_plot(b_value = diccionario['Boosted']['b_mean'],
                                       a_value = diccionario['Boosted']['a_mean'],
                                       ax_h = ax[0, index_],
                                       magnitud_minima = min_max_GR[0],
                                       magnitud_maxima = min_max_GR[1])
  if index_ > 0:
    ax[0, index_].set_ylabel('')
  ax[0, index_].set_xlabel('')
  ax[0, index_].set_title(f'{titles_[index_]} - All depths')

# Someros
for index_, diccionario in enumerate([diccionario_FC_somero,
                                      diccionario_BSN_somero,
                                      diccionario_CC_somero]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes = diccionario['get_N']['m'],
                                          ax_h = ax[1, index_],
                                          mc = diccionario['Boosted']['mc_mean'].round(2),
                                          magnitud_maxima= mag_max)
  sup.plots.GutenbergRichter_line_plot(b_value = diccionario['Boosted']['b_mean'],
                                       a_value = diccionario['Boosted']['a_mean'],
                                       ax_h = ax[1, index_],
                                       magnitud_minima = min_max_GR[0],
                                       magnitud_maxima = min_max_GR[1])
  if index_ > 0:
    ax[1, index_].set_ylabel('')
  ax[1, index_].set_xlabel('')
  ax[1, index_].set_title(f'{titles_[index_]} - Depth $\leq{profundidad_corte}$ km')

# Profundos
for index_, diccionario in enumerate([diccionario_FC_profundo,
                                      diccionario_BSN_profundo,
                                      diccionario_CC_profundo]):
  sup.plots.GutenbergRichter_scatter_plot(N_count = diccionario['get_N']['N'],
                                          magnitudes = diccionario['get_N']['m'],
                                          ax_h = ax[2, index_],
                                          mc = diccionario['Boosted']['mc_mean'].round(2),
                                          magnitud_maxima= mag_max)
  sup.plots.GutenbergRichter_line_plot(b_value = diccionario['Boosted']['b_mean'],
                                       a_value = diccionario['Boosted']['a_mean'],
                                       ax_h = ax[2, index_],
                                       magnitud_minima = min_max_GR[0],
                                       magnitud_maxima = min_max_GR[1])
  if index_ > 0:
    ax[2, index_].set_ylabel('')
  ax[2, index_].set_xlabel('')
  ax[2, index_].set_title(f'{titles_[index_]} - Depth $>{profundidad_corte}$ km')

ax[2, 0].set_xlabel('Magnitude')
ax[2, 1].set_xlabel('Magnitude')
ax[2, 2].set_xlabel('Magnitude')

plt.tight_layout()

sup.plots.save_plot(path_save_figuras = path_save_figures,
                    file_name = 'grafico_GR_boosted_',
                    formato = 'png',
                    dpi_ = 300)

plt.show()

# Calculo GR acumulado

Se procederá a calcular los parámetros a-value, b-value y Mc de forma acumulativa. Para ello, el análisis se iniciará en el período mínimo 1993–1994 y, posteriormente, se irá incorporando información de manera progresiva, añadiendo un año a la vez, hasta completar el intervalo 1993–2024.

In [ ]:
print('Año mínimo: ', df_FC['Tiempo'].dt.year.min())
print('Año máximo: ', df_FC['Tiempo'].dt.year.max())

In [ ]:
year_range = np.arange(df_FC['Tiempo'].dt.year.min(),
                       df_FC['Tiempo'].dt.year.max()+1)
year_range

## Todo el catalogo

In [ ]:
diccionario_Acumulado_todos = {}

estadisticos = ['mc_mean', 'mc_std',
                'b_mean', 'b_std',
                'a_mean', 'a_std']

catalogos_ = {'FC': df_FC,
              'BSN': df_BSN,
              'CC': df_CC}


for key, catalogo in catalogos_.items():
  print('\n')
  lista_years = []
  lista_estadisticos_label = []
  lista_estadisticos = []
  print(key)
  catalogo_temp = catalogo.copy()
  catalogo_temp.reset_index(inplace=True, drop=True)
  for i in range(1, len(year_range)):
    years_ = [year_range[0], year_range[i]]
    print(years_)
    filtro_datos = (catalogo_temp['Tiempo'].dt.year >= years_[0]) & (catalogo_temp['Tiempo'].dt.year <= years_[1])
    #filtro_datos = catalogo_temp['Tiempo'].dt.year.isin(year_range[0:i+1])
    print(year_range[0], year_range[i])
    magnitudes_tempo = catalogo_temp['Magnitud'][filtro_datos]
    print('Suma filtro', filtro_datos.sum())
    print('Shape magnitudes', magnitudes_tempo.shape)
    diccionario_temp = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = magnitudes_tempo,
                                                            percentage_data = porcentaje_remuestreo, # 0.8
                                                            magnitud_minima = mag_min,
                                                            magnitud_maxima = mag_max,
                                                            steps_ = steps_mag,
                                                            n_resamples = numero_remuestreos,
                                                            replace_ = reemplazo,
                                                            correcion_m = correcion_mc)

    for estadistico in estadisticos:
      lista_years.append(f'{year_range[0]}-{year_range[i]}')
      lista_estadisticos_label.append(estadistico)
      lista_estadisticos.append(diccionario_temp[estadistico])


  diccionario_Acumulado_todos[key] = {'Años': lista_years,
                                      'Estadistico': lista_estadisticos_label,
                                      'Valor': lista_estadisticos}

### Dataframe

In [ ]:
diccionario_Acumulado_todos.keys()

In [ ]:
diccionario_Acumulado_todos['FC'].keys()

In [ ]:
pd.DataFrame(diccionario_Acumulado_todos['FC']).head()

In [ ]:
diccionario_df_acumulados = {}

for key, diccionario in diccionario_Acumulado_todos.items():
  df_temp = pd.DataFrame(diccionario)
  estadisticos = df_temp['Estadistico'].unique()

  df_vacio = pd.DataFrame(columns = ['Años'])
  df_vacio['Años'] = df_temp['Años'].unique()
  df_vacio['Catalogo'] = key
  #df_vacio.set_index('Años', inplace=True)

  for estadistico in estadisticos:
    df_vacio[estadistico] = df_temp[df_temp['Estadistico'] == estadistico]['Valor'].values

  diccionario_df_acumulados[key] = df_vacio

In [ ]:
diccionario_df_acumulados.keys()

In [ ]:
diccionario_df_acumulados['FC']

In [ ]:
for key, df in diccionario_df_acumulados.items():
  df.to_csv(path_or_buf = os.path.join(path_save_figures, f'df_GR_acumulado_{key}_todos.csv'),
            sep=';',
            decimal=',',
            index=True)

## Eventos someros

In [ ]:
diccionario_Acumulado_someros = {}

estadisticos = ['mc_mean', 'mc_std',
                'b_mean', 'b_std',
                'a_mean', 'a_std']

catalogos_ = {'FC somero': df_FC,
              'BSN somero': df_BSN,
              'CC somero': df_CC}


for key, catalogo in catalogos_.items():
  print('\n')
  lista_years = []
  lista_estadisticos_label = []
  lista_estadisticos = []
  filtro_datos = catalogo['Profundidad [km]'] <= profundidad_corte
  catalogo_temp = catalogo[filtro_datos].copy()
  catalogo_temp.reset_index(inplace=True, drop=True)
  print(key)
  for i in range(1, len(year_range)):
    years_ = [year_range[0], year_range[i]]
    print(years_)
    filtro_datos = (catalogo_temp['Tiempo'].dt.year >= years_[0]) & (catalogo_temp['Tiempo'].dt.year <= years_[1])
    #filtro_datos = catalogo_temp['Tiempo'].dt.year.isin([year_range[0], year_range[i]])
    print(year_range[0], year_range[i])
    magnitudes_tempo = catalogo_temp['Magnitud'][filtro_datos]
    print('Suma filtro', filtro_datos.sum())
    print('Shape magnitudes', magnitudes_tempo.shape)
    diccionario_temp = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = magnitudes_tempo,
                                                            percentage_data = porcentaje_remuestreo, # 0.8
                                                            magnitud_minima = mag_min,
                                                            magnitud_maxima = mag_max,
                                                            steps_ = steps_mag,
                                                            n_resamples = numero_remuestreos,
                                                            replace_ = reemplazo,
                                                            correcion_m = correcion_mc)

    for estadistico in estadisticos:
      lista_years.append(f'{year_range[0]}-{year_range[i]}')
      lista_estadisticos_label.append(estadistico)
      lista_estadisticos.append(diccionario_temp[estadistico])

  diccionario_Acumulado_someros[key] = {'Años': lista_years,
                                      'Estadistico': lista_estadisticos_label,
                                      'Valor': lista_estadisticos}

### Dataframe

In [ ]:
diccionario_Acumulado_someros.keys()

In [ ]:
diccionario_Acumulado_someros['FC somero'].keys()

In [ ]:
pd.DataFrame(diccionario_Acumulado_someros['FC somero']).head()

In [ ]:
diccionario_df_acumulados_somero = {}

for key, diccionario in diccionario_Acumulado_someros.items():
  df_temp = pd.DataFrame(diccionario)
  estadisticos = df_temp['Estadistico'].unique()

  df_vacio = pd.DataFrame(columns = ['Años'])
  df_vacio['Años'] = df_temp['Años'].unique()
  df_vacio['Catalogo'] = key
  #df_vacio.set_index('Años', inplace=True)

  for estadistico in estadisticos:
    df_vacio[estadistico] = df_temp[df_temp['Estadistico'] == estadistico]['Valor'].values

  diccionario_df_acumulados_somero[key] = df_vacio

In [ ]:
diccionario_df_acumulados_somero.keys()

In [ ]:
diccionario_df_acumulados_somero['FC somero']

In [ ]:
for key, df in diccionario_df_acumulados_somero.items():
  df.to_csv(path_or_buf = os.path.join(path_save_figures, f'df_GR_acumulado_{key}_.csv'),
            sep=';',
            decimal=',',
            index=True)

## Eventos profundos

In [ ]:
diccionario_Acumulado_profundo = {}

estadisticos = ['mc_mean', 'mc_std',
                'b_mean', 'b_std',
                'a_mean', 'a_std']

catalogos_ = {'FC profundo': df_FC,
              'BSN profundo': df_BSN,
              'CC profundo': df_CC}


for key, catalogo in catalogos_.items():
  print('\n')
  lista_years = []
  lista_estadisticos_label = []
  lista_estadisticos = []
  filtro_datos = catalogo['Profundidad [km]'] > profundidad_corte
  catalogo_temp = catalogo[filtro_datos].copy()
  catalogo_temp.reset_index(inplace=True, drop=True)
  print(key)
  for i in range(1, len(year_range)):
    years_ = [year_range[0], year_range[i]]
    print(years_)
    filtro_datos = (catalogo_temp['Tiempo'].dt.year >= years_[0]) & (catalogo_temp['Tiempo'].dt.year <= years_[1])
    #filtro_datos = catalogo_temp['Tiempo'].dt.year.isin([year_range[0], year_range[i]])
    print(year_range[0], year_range[i])
    magnitudes_tempo = catalogo_temp['Magnitud'][filtro_datos]
    print('Suma filtro', filtro_datos.sum())
    print('Shape magnitudes', magnitudes_tempo.shape)
    diccionario_temp = sup.stats.get_GutenbergRichter_values_boosted_2(magnitudes = magnitudes_tempo,
                                                            percentage_data = porcentaje_remuestreo, # 0.8
                                                            magnitud_minima = mag_min,
                                                            magnitud_maxima = mag_max,
                                                            steps_ = steps_mag,
                                                            n_resamples = numero_remuestreos,
                                                            replace_ = reemplazo,
                                                            correcion_m = correcion_mc)

    for estadistico in estadisticos:
      lista_years.append(f'{year_range[0]}-{year_range[i]}')
      lista_estadisticos_label.append(estadistico)
      lista_estadisticos.append(diccionario_temp[estadistico])

  diccionario_Acumulado_profundo[key] = {'Años': lista_years,
                                      'Estadistico': lista_estadisticos_label,
                                      'Valor': lista_estadisticos}

### Dataframe

In [ ]:
diccionario_Acumulado_profundo.keys()

In [ ]:
diccionario_Acumulado_profundo['FC profundo'].keys()

In [ ]:
pd.DataFrame(diccionario_Acumulado_profundo['FC profundo']).head()

In [ ]:
diccionario_df_acumulados_profundo = {}

for key, diccionario in diccionario_Acumulado_profundo.items():
  df_temp = pd.DataFrame(diccionario)
  estadisticos = df_temp['Estadistico'].unique()

  df_vacio = pd.DataFrame(columns = ['Años'])
  df_vacio['Años'] = df_temp['Años'].unique()
  df_vacio['Catalogo'] = key
  #df_vacio.set_index('Años', inplace=True)

  for estadistico in estadisticos:
    df_vacio[estadistico] = df_temp[df_temp['Estadistico'] == estadistico]['Valor'].values

  diccionario_df_acumulados_profundo[key] = df_vacio

In [ ]:
diccionario_df_acumulados_profundo.keys()

In [ ]:
diccionario_df_acumulados_profundo['FC profundo']

In [ ]:
for key, df in diccionario_df_acumulados_profundo.items():
  df.to_csv(path_or_buf = os.path.join(path_save_figures, f'df_GR_acumulado_{key}_.csv'),
            sep=';',
            decimal=',',
            index=True)

## Grafico GR acumulado

In [ ]:
diccionario_df_acumulados.keys()

In [ ]:
diccionario_df_acumulados_somero.keys()

In [ ]:
diccionario_df_acumulados_profundo.keys()

In [ ]:
variables = {'b-value': ['b_mean', 'b_std'],
             'a-value': ['a_mean', 'a_std'],
             'Mc': ['mc_mean', 'mc_std']}

for var_, estadistico_ in variables.items():
  fig, ax = plt.subplots(ncols=1, nrows=3, figsize=(7,9), sharex=True)

  # Todos
  for catalogo_, dataFrame_ in diccionario_df_acumulados.items():
    ax[0].errorbar(x = year_range[1:],
                   y = dataFrame_[estadistico_[0]],
                   yerr = dataFrame_[estadistico_[1]],
                   fmt = '-o',
                   label = catalogo_[0:3])
  ax[0].set_xlabel('')
  ax[0].legend()
  ax[0].set_ylabel(f'{var_}')
  ax[0].grid(ls='--', c='gray', alpha=0.7)

  # Someros
  for catalogo_, dataFrame_ in diccionario_df_acumulados_somero.items():
    ax[1].errorbar(x = year_range[1:],
                   y = dataFrame_[estadistico_[0]],
                   yerr = dataFrame_[estadistico_[1]],
                   fmt = '-o',
                   label = catalogo_[0:3])
  ax[1].set_xlabel('')
  ax[1].legend()
  ax[1].set_ylabel(f'{var_}')
  ax[1].grid(ls='--', c='gray', alpha=0.7)

  # Profundos
  for catalogo_, dataFrame_ in diccionario_df_acumulados_profundo.items():
    ax[2].errorbar(x = year_range[1:],
                   y = dataFrame_[estadistico_[0]],
                   yerr = dataFrame_[estadistico_[1]],
                   fmt = '-o',
                   label = catalogo_[0:3])
  #ax[2].set_xlabel('')
  ax[2].legend()
  ax[2].set_ylabel(f'{var_}')
  ax[2].grid(ls='--', c='gray', alpha=0.7)


  ax[0].set_title(f'All depths')
  ax[1].set_title(f'Depth $\leq{profundidad_corte}$ km')
  ax[2].set_title(f'Depth $>{profundidad_corte}$ km')

  plt.tight_layout()

  sup.plots.save_plot(path_save_figuras = path_save_figures,
                      file_name = f'GR_{var_}_acumulado',
                      formato = 'png',
                      dpi_ = 300)

  plt.show()
  print('\n')

# Fin